/**
 * Editorial context per circuit: what races it hosts and why it's special.
 * One tight blurb per circuit, localised in all six languages, shown on the
 * circuit hub. (Le Mans has its own richer content via the bespoke template.)
 */
import type { Locale } from "@/lib/types";

export const ABOUT_HEADING: Record<Locale, string> = {
  en: "The circuit",
  fr: "Le circuit",
  nl: "Het circuit",
  de: "Die Strecke",
  it: "Il circuito",
  es: "El circuito",
};

const CONTEXT: Record<string, Record<Locale, string>> = {
  silverstone: {
    en: "Silverstone is the birthplace of Formula 1: it hosted the very first World Championship Grand Prix in 1950. Fast, flowing and wind-swept on a former WWII airfield, its high-speed sweeps through Maggotts and Becketts are revered by drivers, and the British Grand Prix draws one of the sport's biggest and most passionate crowds.",
    fr: "Silverstone est le berceau de la Formule 1 : il a accueilli le tout premier Grand Prix du Championnat du monde en 1950. Rapide, fluide et balayé par le vent sur un ancien aérodrome de la Seconde Guerre mondiale, ses enchaînements à haute vitesse de Maggotts et Becketts sont vénérés des pilotes, et le Grand Prix de Grande-Bretagne attire l'un des publics les plus nombreux et passionnés du sport.",
    nl: "Silverstone is de bakermat van de Formule 1: hier werd in 1950 de allereerste WK-Grand Prix verreden. Snel, vloeiend en winderig op een voormalig vliegveld uit WO II, met de razendsnelle bochtencombinatie Maggotts–Becketts die door coureurs wordt vereerd. De Britse Grand Prix trekt een van de grootste en meest gepassioneerde publieken van de sport.",
    de: "Silverstone ist die Geburtsstätte der Formel 1: 1950 fand hier der allererste Weltmeisterschafts-Grand-Prix statt. Schnell, fließend und windumtost auf einem ehemaligen Flugplatz aus dem Zweiten Weltkrieg, werden die Hochgeschwindigkeitspassagen Maggotts und Becketts von den Fahrern verehrt, und der Große Preis von Großbritannien zieht eines der größten und leidenschaftlichsten Publikum des Sports an.",
    it: "Silverstone è la culla della Formula 1: ospitò il primissimo Gran Premio del Mondiale nel 1950. Veloce, scorrevole e spazzato dal vento su un ex aeroporto della Seconda guerra mondiale, le sue rapidissime esse di Maggotts e Becketts sono venerate dai piloti, e il Gran Premio di Gran Bretagna richiama uno dei pubblici più numerosi e appassionati dello sport.",
    es: "Silverstone es la cuna de la Fórmula 1: acogió el primerísimo Gran Premio del Mundial en 1950. Rápido, fluido y azotado por el viento sobre un antiguo aeródromo de la Segunda Guerra Mundial, sus enlaces de alta velocidad de Maggotts y Becketts son venerados por los pilotos, y el Gran Premio de Gran Bretaña atrae a uno de los públicos más numerosos y apasionados del deporte.",
  },
  spa: {
    en: "Spa-Francorchamps is widely considered the greatest road course in the world. Carved through the Ardennes forest, it climbs and plunges over 7 km, with the legendary uphill Eau Rouge–Raidillon complex taken almost flat out. Its unpredictable micro-climate makes every race a spectacle, from the Belgian Grand Prix to the WEC's 6 Hours and the 24 Hours of Spa.",
    fr: "Spa-Francorchamps est largement considéré comme le plus beau tracé routier du monde. Taillé dans la forêt des Ardennes, il grimpe et plonge sur plus de 7 km, avec le légendaire enchaînement en montée Eau Rouge–Raidillon pris quasiment à fond. Son micro-climat imprévisible fait de chaque course un spectacle, du Grand Prix de Belgique aux 6 Heures du WEC et aux 24 Heures de Spa.",
    nl: "Spa-Francorchamps geldt als het mooiste wegcircuit ter wereld. Uitgehakt in het Ardennenbos klimt en duikt het over meer dan 7 km, met het legendarische klimmende complex Eau Rouge–Raidillon dat bijna vol wordt genomen. Het grillige microklimaat maakt elke race tot een spektakel, van de Belgische Grand Prix tot de 6 Uur van het WEC en de 24 Uur van Spa.",
    de: "Spa-Francorchamps gilt weithin als die schönste Rennstrecke der Welt. Durch den Ardennenwald geschlagen, steigt und stürzt sie über 7 km, mit der legendären Bergauf-Passage Eau Rouge–Raidillon, die fast voll gefahren wird. Ihr unberechenbares Mikroklima macht jedes Rennen zum Spektakel, vom Großen Preis von Belgien über die 6 Stunden der WEC bis zum 24-Stunden-Rennen von Spa.",
    it: "Spa-Francorchamps è considerato il più bel tracciato stradale del mondo. Scavato nella foresta delle Ardenne, sale e precipita per oltre 7 km, con il leggendario complesso in salita Eau Rouge–Raidillon preso quasi a tavoletta. Il suo microclima imprevedibile rende ogni gara uno spettacolo, dal Gran Premio del Belgio alle 6 Ore del WEC e alla 24 Ore di Spa.",
    es: "Spa-Francorchamps está considerado el mejor trazado de carretera del mundo. Tallado en el bosque de las Ardenas, sube y se precipita a lo largo de más de 7 km, con el legendario complejo en subida Eau Rouge–Raidillon tomado casi a fondo. Su microclima impredecible convierte cada carrera en un espectáculo, del Gran Premio de Bélgica a las 6 Horas del WEC y las 24 Horas de Spa.",
  },
  zandvoort: {
    en: "Set among the North Sea dunes, Zandvoort is a tight, old-school rollercoaster with dramatic banked corners at Turn 3 and the final Arie Luyendyk bend. The Dutch Grand Prix returned in 2021 to a sea of orange for Max Verstappen, creating one of the most electric atmospheres on the calendar.",
    fr: "Niché dans les dunes de la mer du Nord, Zandvoort est des montagnes russes serrées à l'ancienne, avec des virages relevés spectaculaires au virage 3 et à l'ultime courbe Arie Luyendyk. Le Grand Prix des Pays-Bas est revenu en 2021 dans une mer d'orange pour Max Verstappen, créant l'une des ambiances les plus électriques du calendrier.",
    nl: "Tussen de Noordzeeduinen is Zandvoort een nauwe, ouderwetse achtbaan met spectaculaire kombochten in bocht 3 en de afsluitende Arie Luyendykbocht. De Dutch Grand Prix keerde in 2021 terug in een oranje zee voor Max Verstappen en zorgt voor een van de meest elektrische sferen van de kalender.",
    de: "Eingebettet in die Nordseedünen ist Zandvoort eine enge Achterbahn alter Schule mit spektakulär überhöhten Kurven in Kurve 3 und der abschließenden Arie-Luyendyk-Kurve. Der Große Preis der Niederlande kehrte 2021 in einem Meer aus Orange für Max Verstappen zurück und sorgt für eine der elektrisierendsten Atmosphären des Kalenders.",
    it: "Incastonato tra le dune del Mare del Nord, Zandvoort è un ottovolante stretto e d'altri tempi, con spettacolari curve sopraelevate alla 3 e alla conclusiva Arie Luyendyk. Il Gran Premio d'Olanda è tornato nel 2021 in un mare d'arancione per Max Verstappen, creando una delle atmosfere più elettriche del calendario.",
    es: "Entre las dunas del Mar del Norte, Zandvoort es una montaña rusa estrecha y a la antigua, con espectaculares curvas peraltadas en la 3 y en la última Arie Luyendyk. El Gran Premio de los Países Bajos volvió en 2021 en un mar naranja por Max Verstappen, creando uno de los ambientes más eléctricos del calendario.",
  },
  nurburgring: {
    en: "The Nürburgring is motorsport's 'Green Hell'. While modern racing uses the GP-Strecke, the circuit's soul is the 20 km Nordschleife, the most demanding track ever built. Each year the ADAC 24 Hours turns the Eifel forest into a 200,000-strong festival of endurance racing and trackside camping.",
    fr: "Le Nürburgring, c'est « l'Enfer Vert » du sport auto. Si la course moderne emprunte le GP-Strecke, l'âme du circuit reste la Nordschleife de 20 km, le tracé le plus exigeant jamais construit. Chaque année, les 24 Heures de l'ADAC transforment la forêt de l'Eifel en un festival de plus de 200 000 personnes, entre endurance et camping au bord de la piste.",
    nl: "De Nürburgring is de 'Grüne Hölle' van de motorsport. Moderne races rijden op de GP-Strecke, maar de ziel van het circuit is de 20 km lange Nordschleife, het veeleisendste circuit ooit gebouwd. Elk jaar maken de ADAC 24 Uur van het Eifelbos een festival van meer dan 200.000 bezoekers, endurance en kamperen langs de baan.",
    de: "Der Nürburgring ist die „Grüne Hölle“ des Motorsports. Während moderne Rennen auf der GP-Strecke stattfinden, ist die Seele der Strecke die 20 km lange Nordschleife, die anspruchsvollste Rennstrecke, die je gebaut wurde. Jedes Jahr verwandeln die ADAC 24 Stunden den Eifelwald in ein Festival mit über 200.000 Fans, Langstreckensport und Camping an der Strecke.",
    it: "Il Nürburgring è l'«Inferno Verde» del motorsport. Le gare moderne usano la GP-Strecke, ma l'anima del circuito è la Nordschleife di 20 km, il tracciato più impegnativo mai costruito. Ogni anno la 24 Ore dell'ADAC trasforma la foresta dell'Eifel in un festival di oltre 200.000 persone, tra endurance e campeggio a bordo pista.",
    es: "El Nürburgring es el «Infierno Verde» del motor. Aunque las carreras modernas usan el GP-Strecke, el alma del circuito es el Nordschleife de 20 km, el trazado más exigente jamás construido. Cada año las 24 Horas del ADAC convierten el bosque del Eifel en un festival de más de 200.000 personas, entre resistencia y acampada junto a la pista.",
  },
  monza: {
    en: "Monza is the Temple of Speed. One of the oldest purpose-built circuits in the world (1922), it's a flat-out blast through historic parkland with the lowest-downforce setups and longest full-throttle sections in Formula 1. The Italian Grand Prix unleashes Ferrari's tifosi, who flood the track in their tens of thousands after the race.",
    fr: "Monza, c'est le Temple de la Vitesse. L'un des plus anciens autodromes permanents au monde (1922), c'est une déferlante à fond dans un parc historique, avec les réglages les plus dégagés et les plus longues portions pleins gaz de la Formule 1. Le Grand Prix d'Italie déchaîne les tifosi de Ferrari, qui envahissent la piste par dizaines de milliers après la course.",
    nl: "Monza is de Tempel van de Snelheid. Een van de oudste vaste circuits ter wereld (1922) en een vlucht op volle snelheid door een historisch park, met de laagste downforce-afstellingen en de langste vol-gas-stukken van de Formule 1. De Grand Prix van Italië ontketent de tifosi van Ferrari, die na de race met tienduizenden de baan op stromen.",
    de: "Monza ist der Tempel der Geschwindigkeit. Als eine der ältesten permanenten Rennstrecken der Welt (1922) ist sie ein Vollgas-Ritt durch einen historischen Park, mit den abtriebsärmsten Set-ups und den längsten Vollgaspassagen der Formel 1. Der Große Preis von Italien entfesselt Ferraris Tifosi, die nach dem Rennen zu Zehntausenden die Strecke fluten.",
    it: "Monza è il Tempio della Velocità. Uno dei più antichi autodromi permanenti al mondo (1922), è una cavalcata a tavoletta in un parco storico, con i set-up più scarichi e i rettilinei a tutto gas più lunghi della Formula 1. Il Gran Premio d'Italia scatena i tifosi della Ferrari, che a fine gara invadono la pista a decine di migliaia.",
    es: "Monza es el Templo de la Velocidad. Uno de los autódromos permanentes más antiguos del mundo (1922), es un lanzamiento a fondo por un parque histórico, con las puestas a punto más descargadas y los tramos a pleno gas más largos de la Fórmula 1. El Gran Premio de Italia desata a los tifosi de Ferrari, que tras la carrera inundan la pista por decenas de miles.",
  },
  spielberg: {
    en: "Tucked into the green Styrian hills, the Red Bull Ring is short, sharp and brutally fast, a handful of corners strung between steep climbs and descents with stunning Alpine views. Owned by Red Bull, it hosts both the Austrian Grand Prix and a MotoGP round, and the orange-clad fans turn the hillsides into a party.",
    fr: "Blotti dans les collines verdoyantes de Styrie, le Red Bull Ring est court, incisif et brutalement rapide : une poignée de virages reliés par des montées et descentes abruptes, avec des vues alpines superbes. Propriété de Red Bull, il accueille à la fois le Grand Prix d'Autriche et une manche de MotoGP, et les fans en orange transforment les collines en fête.",
    nl: "Verscholen in de groene heuvels van Stiermarken is de Red Bull Ring kort, scherp en bikkelhard snel: een handvol bochten tussen steile klimmen en afdalingen met prachtige Alpenuitzichten. In handen van Red Bull, gastheer van zowel de Grand Prix van Oostenrijk als een MotoGP-race, en de oranje fans maken er op de heuvels een feest van.",
    de: "Eingebettet in die grünen steirischen Hügel ist der Red Bull Ring kurz, scharf und brutal schnell: eine Handvoll Kurven zwischen steilen Anstiegen und Abfahrten mit traumhaftem Alpenblick. Im Besitz von Red Bull, austragend sowohl den Großen Preis von Österreich als auch ein MotoGP-Rennen, und die orange gekleideten Fans machen die Hänge zur Party.",
    it: "Incastonato nelle verdi colline della Stiria, il Red Bull Ring è corto, deciso e brutalmente veloce: una manciata di curve tra ripide salite e discese, con splendide viste sulle Alpi. Di proprietà della Red Bull, ospita sia il Gran Premio d'Austria sia una gara di MotoGP, e i tifosi vestiti d'arancione trasformano le colline in una festa.",
    es: "Enclavado en las verdes colinas de Estiria, el Red Bull Ring es corto, incisivo y brutalmente rápido: un puñado de curvas entre subidas y bajadas pronunciadas con espectaculares vistas alpinas. Propiedad de Red Bull, acoge tanto el Gran Premio de Austria como una cita del MotoGP, y los aficionados de naranja convierten las laderas en una fiesta.",
  },
  monaco: {
    en: "Monaco is the crown jewel of motorsport, a glamorous, unforgiving street circuit threading between the harbour, the casino and the barriers of Monte Carlo. There is no margin for error and almost nowhere to overtake, which makes qualifying everything. Winning here is one of the three legs of the sport's Triple Crown.",
    fr: "Monaco est le joyau du sport automobile : un circuit urbain glamour et impitoyable qui se faufile entre le port, le casino et les rails de Monte-Carlo. Aucune marge d'erreur, presque aucun endroit pour dépasser : les qualifications font tout. Gagner ici est l'une des trois étapes de la Triple Couronne du sport.",
    nl: "Monaco is het kroonjuweel van de autosport: een glamoureus, genadeloos stratencircuit dat zich tussen de haven, het casino en de vangrails van Monte Carlo door wurmt. Geen foutmarge en bijna nergens om in te halen, waardoor de kwalificatie alles is. Hier winnen is een van de drie onderdelen van de Triple Crown.",
    de: "Monaco ist das Kronjuwel des Motorsports: ein glamouröser, gnadenloser Stadtkurs, der sich zwischen Hafen, Casino und den Leitplanken von Monte Carlo hindurchwindet. Es gibt keinen Spielraum für Fehler und kaum eine Stelle zum Überholen, weshalb das Qualifying alles ist. Ein Sieg hier ist eines der drei Glieder der Triple Crown.",
    it: "Monaco è il gioiello del motorsport: un circuito cittadino glamour e spietato che si snoda tra il porto, il casinò e le barriere di Monte Carlo. Non c'è margine d'errore e quasi nessun punto per sorpassare, perciò le qualifiche sono tutto. Vincere qui è una delle tre prove della Tripla Corona.",
    es: "Mónaco es la joya de la corona del motor: un circuito urbano glamuroso e implacable que se cuela entre el puerto, el casino y las protecciones de Montecarlo. No hay margen de error y casi ningún sitio para adelantar, por lo que la clasificación lo es todo. Ganar aquí es una de las tres patas de la Triple Corona.",
  },
  barcelona: {
    en: "The Circuit de Barcelona-Catalunya is the sport's ultimate proving ground: teams test here all winter, so every corner is known by heart. Its mix of high-speed corners and a tight final sector punishes any weakness in a car, and it hosts both Formula 1 and the Catalan MotoGP near the buzz of Barcelona.",
    fr: "Le Circuit de Barcelona-Catalunya est le terrain d'essai par excellence : les équipes y roulent tout l'hiver, si bien que chaque virage est connu par cœur. Son mélange de courbes rapides et de dernier secteur serré sanctionne la moindre faiblesse d'une voiture, et il accueille la Formule 1 comme le MotoGP de Catalogne, tout près de l'effervescence de Barcelone.",
    nl: "Het Circuit de Barcelona-Catalunya is het ultieme testterrein: teams testen er de hele winter, dus elke bocht kennen ze uit het hoofd. De mix van snelle bochten en een nauwe slotsector straft elke zwakte van een auto af, en het is gastheer van zowel de Formule 1 als de Catalaanse MotoGP, vlak bij de drukte van Barcelona.",
    de: "Der Circuit de Barcelona-Catalunya ist der ultimative Prüfstand: Teams testen hier den ganzen Winter, sodass jede Kurve in- und auswendig bekannt ist. Die Mischung aus Hochgeschwindigkeitskurven und einem engen Schlusssektor bestraft jede Schwäche eines Autos, und er beherbergt sowohl die Formel 1 als auch die MotoGP von Katalonien, nahe dem Trubel von Barcelona.",
    it: "Il Circuit de Barcelona-Catalunya è il banco di prova per eccellenza: i team ci girano tutto l'inverno, perciò ogni curva è conosciuta a memoria. Il mix di curve veloci e un ultimo settore stretto punisce ogni debolezza di una vettura, e ospita sia la Formula 1 sia la MotoGP della Catalogna, a due passi dal fermento di Barcellona.",
    es: "El Circuit de Barcelona-Catalunya es el banco de pruebas por excelencia: los equipos ruedan aquí todo el invierno, así que cada curva se conoce de memoria. Su mezcla de curvas rápidas y un último sector estrecho castiga cualquier debilidad de un coche, y acoge tanto la Fórmula 1 como el MotoGP de Cataluña, junto al bullicio de Barcelona.",
  },
  madrid: {
    en: "New for 2026, Madrid's 'Madring' is a bold semi-street circuit wrapped around the IFEMA exhibition grounds, bringing Formula 1 into the Spanish capital. With a metro line linking the airport, the track and the city centre, it's the most accessible new venue on the calendar and the freshest ticket in motorsport.",
    fr: "Nouveau en 2026, le « Madring » de Madrid est un audacieux circuit semi-urbain enroulé autour du parc des expositions IFEMA, amenant la Formule 1 dans la capitale espagnole. Avec une ligne de métro reliant l'aéroport, la piste et le centre-ville, c'est le nouveau site le plus accessible du calendrier et le billet le plus tendance du sport auto.",
    nl: "Nieuw in 2026 is Madrids 'Madring' een gedurfd semi-stratencircuit rond het IFEMA-beursterrein, dat de Formule 1 naar de Spaanse hoofdstad brengt. Met een metrolijn die de luchthaven, het circuit en het centrum verbindt, is het de best bereikbare nieuwe locatie van de kalender en het verste ticket in de motorsport.",
    de: "Neu 2026 ist Madrids „Madring“ ein kühner Halb-Stadtkurs rund um das Messegelände IFEMA, der die Formel 1 in die spanische Hauptstadt bringt. Mit einer Metrolinie, die Flughafen, Strecke und Stadtzentrum verbindet, ist er der am besten erreichbare neue Austragungsort des Kalenders und das frischeste Ticket im Motorsport.",
    it: "Novità del 2026, il «Madring» di Madrid è un audace circuito semicittadino attorno al polo fieristico IFEMA, che porta la Formula 1 nella capitale spagnola. Con una linea della metro che collega aeroporto, pista e centro città, è la nuova sede più accessibile del calendario e il biglietto più fresco del motorsport.",
    es: "Nuevo en 2026, el «Madring» de Madrid es un audaz circuito semiurbano alrededor del recinto ferial de IFEMA, que lleva la Fórmula 1 a la capital española. Con una línea de metro que une el aeropuerto, el trazado y el centro, es la nueva sede más accesible del calendario y la entrada más fresca del motor.",
  },
  hungaroring: {
    en: "Often called 'Monaco without the walls', the Hungaroring is a tight, twisty ribbon where track position is king and overtaking is hard-won. Just outside Budapest, it bakes in the high-summer heat and rewards a well-balanced car, while the city's thermal baths and nightlife make it a favourite race-week destination.",
    fr: "Souvent surnommé « Monaco sans les murs », le Hungaroring est un ruban serré et sinueux où la position en piste est reine et les dépassements chèrement acquis. Aux portes de Budapest, il cuit sous la chaleur de plein été et récompense une voiture bien équilibrée, tandis que les bains thermaux et la vie nocturne de la ville en font une destination prisée.",
    nl: "Vaak 'Monaco zonder de muren' genoemd, is de Hungaroring een nauw, kronkelig lint waar baanpositie koning is en inhalen moeizaam gaat. Net buiten Boedapest bakt het in de hoogzomerse hitte en beloont het een goed gebalanceerde auto, terwijl de thermale baden en het nachtleven van de stad er een geliefde bestemming van maken.",
    de: "Oft „Monaco ohne Mauern“ genannt, ist der Hungaroring ein enges, kurvenreiches Band, auf dem die Streckenposition König ist und Überholen schwer erkämpft wird. Direkt vor Budapest brutzelt er in der Hochsommerhitze und belohnt ein gut ausbalanciertes Auto, während die Thermalbäder und das Nachtleben der Stadt ihn zu einem beliebten Ziel machen.",
    it: "Spesso chiamato «Monaco senza muri», l'Hungaroring è un nastro stretto e tortuoso dove la posizione in pista è regina e i sorpassi si conquistano a fatica. Alle porte di Budapest, cuoce nella calura di piena estate e premia una vettura ben bilanciata, mentre le terme e la vita notturna della città ne fanno una meta amata.",
    es: "A menudo llamado «Mónaco sin muros», el Hungaroring es una cinta estrecha y revirada donde la posición en pista es reina y adelantar cuesta mucho. A las afueras de Budapest, se cuece bajo el calor de pleno verano y premia un coche bien equilibrado, mientras que los baños termales y la vida nocturna de la ciudad lo hacen un destino muy querido.",
  },
  imola: {
    en: "Imola is one of racing's great old-school circuits: narrow, fast and flowing anticlockwise through the Santerno valley, steeped in history and named after Enzo and Dino Ferrari. Now opening the WEC endurance season with the 6 Hours of Imola, it remains a deeply atmospheric driver's track in the heart of Italy's Motor Valley.",
    fr: "Imola est l'un des grands circuits à l'ancienne : étroit, rapide et fluide dans le sens antihoraire à travers la vallée du Santerno, chargé d'histoire et baptisé du nom d'Enzo et Dino Ferrari. Désormais ouverture de la saison d'endurance WEC avec les 6 Heures d'Imola, il reste un tracé de pilotes à l'atmosphère intense, au cœur de la Motor Valley italienne.",
    nl: "Imola is een van de grote ouderwetse circuits: smal, snel en vloeiend tegen de klok in door het Santerno-dal, doordrenkt van geschiedenis en vernoemd naar Enzo en Dino Ferrari. Nu opent het het WEC-enduranceseizoen met de 6 Uur van Imola en blijft het een sfeervol coureurscircuit in het hart van de Italiaanse Motor Valley.",
    de: "Imola ist eine der großen Rennstrecken alter Schule: eng, schnell und im Gegenuhrzeigersinn fließend durch das Santerno-Tal, geschichtsträchtig und nach Enzo und Dino Ferrari benannt. Heute eröffnet sie die WEC-Langstreckensaison mit dem 6-Stunden-Rennen von Imola und bleibt eine atmosphärische Fahrerstrecke im Herzen der italienischen Motor Valley.",
    it: "Imola è uno dei grandi circuiti d'altri tempi: stretto, veloce e scorrevole in senso antiorario nella valle del Santerno, ricco di storia e intitolato a Enzo e Dino Ferrari. Oggi apre la stagione endurance del WEC con la 6 Ore di Imola e resta un tracciato per piloti dall'atmosfera intensa, nel cuore della Motor Valley italiana.",
    es: "Imola es uno de los grandes circuitos a la antigua: estrecho, rápido y fluido en sentido antihorario por el valle del Santerno, cargado de historia y bautizado con el nombre de Enzo y Dino Ferrari. Ahora abre la temporada de resistencia del WEC con las 6 Horas de Imola y sigue siendo un trazado de pilotos con un ambiente intenso, en el corazón de la Motor Valley italiana.",
  },
  assen: {
    en: "Assen is the 'Cathedral of Motorcycling', the only venue to have hosted a motorcycle Grand Prix every year since the World Championship began in 1949. Its flowing, fast layout was built for two wheels, and the Dutch TT in late June draws a vast, knowledgeable crowd on one of road racing's great pilgrimages.",
    fr: "Assen est la « Cathédrale de la moto », le seul site à avoir accueilli un Grand Prix moto chaque année depuis la création du Championnat du monde en 1949. Son tracé fluide et rapide a été conçu pour les deux-roues, et le Dutch TT, fin juin, attire un public immense et connaisseur, lors de l'un des grands pèlerinages de la course sur route.",
    nl: "Assen is de 'Kathedraal van de motorsport', de enige locatie die sinds het begin van het WK in 1949 elk jaar een motor-Grand Prix heeft gehouden. De vloeiende, snelle lay-out is gebouwd voor twee wielen, en de Dutch TT eind juni trekt een enorm, deskundig publiek tijdens een van de grote bedevaarten van het wegracen.",
    de: "Assen ist die „Kathedrale des Motorradsports“, der einzige Ort, der seit Beginn der Weltmeisterschaft 1949 jedes Jahr einen Motorrad-Grand-Prix ausgetragen hat. Sein fließendes, schnelles Layout wurde für zwei Räder gebaut, und die Dutch TT Ende Juni zieht ein riesiges, kundiges Publikum auf einer der großen Pilgerfahrten des Straßenrennsports an.",
    it: "Assen è la «Cattedrale del motociclismo», l'unica sede ad aver ospitato un Gran Premio moto ogni anno dall'inizio del Mondiale nel 1949. Il tracciato scorrevole e veloce è nato per le due ruote, e il Dutch TT a fine giugno richiama un pubblico enorme ed esperto, in uno dei grandi pellegrinaggi delle corse su strada.",
    es: "Assen es la «Catedral del motociclismo», la única sede que ha acogido un Gran Premio de motos cada año desde que empezó el Mundial en 1949. Su trazado fluido y rápido se construyó para dos ruedas, y el Dutch TT, a finales de junio, atrae a un público inmenso y entendido en una de las grandes peregrinaciones de las carreras en ruta.",
  },
  mugello: {
    en: "Owned by Ferrari and set in the rolling Tuscan hills, Mugello is a breathtaking flow of fast, sweeping corners crowned by a gut-punch main straight. It's a rider's and driver's dream, and the Italian MotoGP turns the surrounding hillsides yellow with the camped-out fans born of the Valentino Rossi era.",
    fr: "Propriété de Ferrari et niché dans les collines vallonnées de Toscane, Mugello est un enchaînement à couper le souffle de courbes rapides et amples, couronné par une ligne droite vertigineuse. Un rêve de pilotes, et le MotoGP d'Italie teinte de jaune les collines alentour, couvertes des campeurs nés de l'ère Valentino Rossi.",
    nl: "In handen van Ferrari en gelegen in de glooiende Toscaanse heuvels is Mugello een adembenemende aaneenschakeling van snelle, weidse bochten, bekroond door een duizelingwekkend rechte stuk. Een droom voor coureurs, en de Italiaanse MotoGP kleurt de omliggende heuvels geel met de kampeerders uit het tijdperk van Valentino Rossi.",
    de: "Im Besitz von Ferrari und in den sanften Hügeln der Toskana gelegen, ist Mugello ein atemberaubender Fluss schneller, weitläufiger Kurven, gekrönt von einer schwindelerregenden Geraden. Ein Traum für Fahrer, und die MotoGP von Italien färbt die umliegenden Hänge gelb mit den campierenden Fans aus der Ära Valentino Rossi.",
    it: "Di proprietà della Ferrari e immerso nelle dolci colline toscane, il Mugello è una sequenza mozzafiato di curve veloci e ampie, coronata da un rettilineo da brividi. Un sogno per i piloti, e il Gran Premio d'Italia tinge di giallo le colline circostanti, gremite dai tifosi accampati nati nell'era di Valentino Rossi.",
    es: "Propiedad de Ferrari y enclavado en las suaves colinas de la Toscana, Mugello es una sucesión sobrecogedora de curvas rápidas y amplias, coronada por una recta de vértigo. Un sueño para los pilotos, y el MotoGP de Italia tiñe de amarillo las laderas con los aficionados acampados nacidos en la era de Valentino Rossi.",
  },
  jerez: {
    en: "Jerez, in the heart of Andalusia's sherry country, is where MotoGP comes home each spring. Tight, technical and sun-baked, its grandstands and hillsides pack in well over 150,000 fiesta-loving fans for the Spanish round, one of the loudest and most colourful weekends in motorcycle racing.",
    fr: "Jerez, au cœur du pays du xérès en Andalousie, c'est là que le MotoGP rentre à la maison chaque printemps. Serré, technique et écrasé de soleil, ses tribunes et ses collines accueillent bien plus de 150 000 fans en mode fiesta pour la manche d'Espagne, l'un des week-ends les plus bruyants et colorés de la course moto.",
    nl: "Jerez, in het hart van de sherrystreek van Andalusië, is waar MotoGP elke lente thuiskomt. Nauw, technisch en zonovergoten, met tribunes en heuvels die ruim 150.000 feestende fans herbergen voor de Spaanse race, een van de luidste en kleurrijkste weekenden in het motorracen.",
    de: "Jerez, im Herzen des Sherry-Landes Andalusiens, ist der Ort, an dem die MotoGP jedes Frühjahr nach Hause kommt. Eng, technisch und sonnendurchglüht, fassen seine Tribünen und Hänge weit über 150.000 fiestafreudige Fans für den Spanien-Lauf, eines der lautesten und farbenfrohsten Wochenenden im Motorradsport.",
    it: "Jerez, nel cuore della terra dello sherry in Andalusia, è dove la MotoGP torna a casa ogni primavera. Stretto, tecnico e arroventato dal sole, le sue tribune e le sue colline accolgono ben oltre 150.000 tifosi in modalità fiesta per il round spagnolo, uno dei weekend più rumorosi e colorati delle corse in moto.",
    es: "Jerez, en el corazón de la tierra del jerez en Andalucía, es donde MotoGP vuelve a casa cada primavera. Estrecho, técnico y achicharrado por el sol, sus gradas y laderas reúnen a bastante más de 150.000 aficionados en plan fiesta para la cita española, uno de los fines de semana más ruidosos y coloridos del motociclismo.",
  },
  misano: {
    en: "On the Adriatic riviera near Rimini, Misano pairs serious MotoGP racing with one of the best party coastlines in Europe. Named after Marco Simoncelli, it sits in the heartland of Italian motorcycling, and the San Marino Grand Prix fills the beaches and the grandstands in equal measure.",
    fr: "Sur la riviera adriatique près de Rimini, Misano associe un MotoGP de haut niveau à l'un des plus beaux littoraux festifs d'Europe. Baptisé en l'honneur de Marco Simoncelli, il se trouve au cœur du motocyclisme italien, et le Grand Prix de Saint-Marin remplit autant les plages que les tribunes.",
    nl: "Aan de Adriatische riviera bij Rimini combineert Misano serieus MotoGP-racen met een van de beste feestkusten van Europa. Vernoemd naar Marco Simoncelli ligt het in het hart van de Italiaanse motorsport, en de Grand Prix van San Marino vult de stranden en de tribunes in gelijke mate.",
    de: "An der Adriaküste bei Rimini verbindet Misano hochklassigen MotoGP-Sport mit einer der besten Partyküsten Europas. Benannt nach Marco Simoncelli, liegt es im Herzland des italienischen Motorradsports, und der Große Preis von San Marino füllt Strände und Tribünen gleichermaßen.",
    it: "Sulla riviera adriatica vicino a Rimini, Misano unisce una MotoGP di alto livello a una delle coste più festaiole d'Europa. Intitolato a Marco Simoncelli, sorge nel cuore del motociclismo italiano, e il Gran Premio di San Marino riempie spiagge e tribune in egual misura.",
    es: "En la riviera adriática cerca de Rímini, Misano combina un MotoGP de altísimo nivel con una de las mejores costas de fiesta de Europa. Bautizado en honor a Marco Simoncelli, se ubica en el corazón del motociclismo italiano, y el Gran Premio de San Marino llena por igual las playas y las gradas.",
  },
  sachsenring: {
    en: "The Sachsenring is a short, tight, anticlockwise circuit in Saxony famous for its plunging 'Waterfall' left-hander. A fortress of MotoGP form, it regularly draws record German crowds of well over 200,000 across the weekend, packing the natural amphitheatre of hillsides.",
    fr: "Le Sachsenring est un circuit court, serré et antihoraire de Saxe, célèbre pour son gauche plongeant en « cascade ». Forteresse de la forme en MotoGP, il attire régulièrement des foules allemandes record de bien plus de 200 000 personnes sur le week-end, remplissant l'amphithéâtre naturel de ses collines.",
    nl: "De Sachsenring is een kort, nauw circuit tegen de klok in in Saksen, beroemd om de duikende 'Waterval'-linkerbocht. Een bolwerk van MotoGP-vorm dat regelmatig recordpublieken van ruim 200.000 Duitsers over het weekend trekt, die het natuurlijke amfitheater van heuvels vullen.",
    de: "Der Sachsenring ist eine kurze, enge Linkskurs-Strecke in Sachsen, berühmt für die abfallende „Wasserfall“-Linkskurve. Eine Festung der MotoGP-Form, die regelmäßig deutsche Rekordmengen von weit über 200.000 Fans übers Wochenende anzieht, die das natürliche Amphitheater der Hänge füllen.",
    it: "Il Sachsenring è un circuito corto, stretto e antiorario in Sassonia, famoso per la sua sinistra in picchiata, la «cascata». Fortezza della MotoGP, richiama regolarmente folle tedesche record di ben oltre 200.000 persone nel weekend, riempiendo l'anfiteatro naturale delle colline.",
    es: "El Sachsenring es un circuito corto, estrecho y antihorario de Sajonia, famoso por su izquierda en caída, la «cascada». Fortaleza de la forma en MotoGP, atrae con regularidad multitudes alemanas récord de bastante más de 200.000 personas en el fin de semana, llenando el anfiteatro natural de las laderas.",
  },
  portimao: {
    en: "The Autódromo Internacional do Algarve is a spectacular modern rollercoaster of blind crests and elevation changes, plunging through the hills above Portimão. Often the dramatic MotoGP finale, it pairs world-class racing with the beaches and warmth of Portugal's Algarve coast.",
    fr: "L'Autódromo Internacional do Algarve est de spectaculaires montagnes russes modernes faites de bosses aveugles et de dénivelés, plongeant dans les collines au-dessus de Portimão. Souvent la finale haletante du MotoGP, il associe une course de classe mondiale aux plages et à la douceur de la côte de l'Algarve.",
    nl: "Het Autódromo Internacional do Algarve is een spectaculaire moderne achtbaan van blinde toppen en hoogteverschillen, duikend door de heuvels boven Portimão. Vaak de dramatische MotoGP-finale, koppelt het racen van wereldklasse aan de stranden en de warmte van de Portugese Algarve.",
    de: "Das Autódromo Internacional do Algarve ist eine spektakuläre moderne Achterbahn aus blinden Kuppen und Höhenunterschieden, die durch die Hügel über Portimão stürzt. Oft das dramatische MotoGP-Finale, verbindet es Weltklasse-Rennsport mit den Stränden und der Wärme der portugiesischen Algarve.",
    it: "L'Autódromo Internacional do Algarve è uno spettacolare ottovolante moderno fatto di dossi ciechi e dislivelli, che precipita tra le colline sopra Portimão. Spesso il drammatico gran finale della MotoGP, unisce gare di livello mondiale alle spiagge e al tepore della costa dell'Algarve.",
    es: "El Autódromo Internacional do Algarve es una espectacular montaña rusa moderna de lomos ciegos y desniveles, que se precipita por las colinas sobre Portimão. A menudo el dramático final del MotoGP, combina carreras de talla mundial con las playas y la calidez de la costa del Algarve.",
  },
  aragon: {
    en: "Remote and dramatic, MotorLand Aragón rises out of the Spanish countryside near Alcañiz, with a long back straight and a technical, twisty middle sector. Accommodation is scarce in this quiet corner of Aragón, so race-goers spread far and wide for the MotoGP weekend.",
    fr: "Isolé et spectaculaire, MotorLand Aragón surgit de la campagne espagnole près d'Alcañiz, avec une longue ligne droite opposée et un secteur intermédiaire technique et sinueux. L'hébergement est rare dans ce coin tranquille d'Aragon, alors les spectateurs s'éparpillent loin à la ronde pour le week-end de MotoGP.",
    nl: "Afgelegen en spectaculair rijst MotorLand Aragón op uit het Spaanse platteland bij Alcañiz, met een lang achterste rechtstuk en een technische, kronkelige middensector. Overnachtingen zijn schaars in deze rustige hoek van Aragón, dus bezoekers spreiden zich wijd uit voor het MotoGP-weekend.",
    de: "Abgelegen und dramatisch erhebt sich MotorLand Aragón aus der spanischen Landschaft bei Alcañiz, mit einer langen Gegengeraden und einem technischen, kurvigen Mittelsektor. Unterkünfte sind in dieser ruhigen Ecke Aragoniens rar, daher verteilen sich die Besucher fürs MotoGP-Wochenende weit.",
    it: "Isolato e spettacolare, MotorLand Aragón sorge dalla campagna spagnola vicino ad Alcañiz, con un lungo rettilineo opposto e un settore centrale tecnico e tortuoso. Gli alloggi scarseggiano in questo angolo tranquillo dell'Aragona, perciò gli spettatori si distribuiscono in lungo e in largo per il weekend della MotoGP.",
    es: "Aislado y espectacular, MotorLand Aragón se alza del campo español cerca de Alcañiz, con una larga recta opuesta y un sector intermedio técnico y revirado. El alojamiento escasea en este rincón tranquilo de Aragón, así que los espectadores se reparten a lo largo y ancho para el fin de semana del MotoGP.",
  },
  balaton: {
    en: "Brand new to MotoGP for 2026, Balaton Park brings Grand Prix motorcycle racing to the shores of Lake Balaton, Hungary's summer playground. A compact, modern circuit beside Central Europe's largest lake, it pairs first-time race history with a holiday-resort setting of beaches and spa towns.",
    fr: "Tout nouveau au MotoGP en 2026, Balaton Park amène le Grand Prix moto sur les rives du lac Balaton, le terrain de jeu estival de la Hongrie. Circuit compact et moderne au bord du plus grand lac d'Europe centrale, il associe une histoire de course inédite à un décor de villégiature fait de plages et de villes thermales.",
    nl: "Splinternieuw in de MotoGP voor 2026 brengt Balaton Park het motor-Grand-Prix-racen naar de oevers van het Balatonmeer, de zomerspeeltuin van Hongarije. Een compact, modern circuit aan het grootste meer van Centraal-Europa, dat voor het eerst racegeschiedenis koppelt aan een vakantiedecor van stranden en kuuroorden.",
    de: "Brandneu in der MotoGP für 2026 bringt Balaton Park den Motorrad-Grand-Prix an die Ufer des Plattensees, Ungarns sommerlichen Spielplatz. Eine kompakte, moderne Strecke am größten See Mitteleuropas, die erstmalige Renngeschichte mit einer Urlaubskulisse aus Stränden und Kurorten verbindet.",
    it: "Assoluta novità della MotoGP 2026, Balaton Park porta il Gran Premio delle moto sulle rive del lago Balaton, il parco giochi estivo dell'Ungheria. Un circuito compatto e moderno accanto al lago più grande dell'Europa centrale, che unisce una storia di gara inedita a una cornice da villeggiatura fatta di spiagge e città termali.",
    es: "Flamante en MotoGP para 2026, Balaton Park lleva el Gran Premio de motos a las orillas del lago Balatón, el patio de recreo veraniego de Hungría. Un circuito compacto y moderno junto al mayor lago de Europa central, que combina una historia de carreras inédita con un entorno vacacional de playas y pueblos balneario.",
  },
};

export const circuitContext = (key: string, locale: Locale): string | undefined =>
  CONTEXT[key]?.[locale];
