// AUTO-GENERATED by scripts/gen-circuit-ts.mjs from an Apify scrape.
// Do not edit by hand — re-run the generator to refresh.
import type { CircuitHotel, CircuitZone } from "@/data/circuit-data";

export const aragonZones: CircuitZone[] = [
  {
    "key": "alcaniz",
    "name": "Alcañiz",
    "driveMin": 3,
    "ring": 1,
    "count": 6,
    "lat": 41.05118,
    "lng": -0.15249
  }
];

export const aragonHotels: CircuitHotel[] = [
  {
    "name": "Camping La Estanca de Alcañiz",
    "slug": "camping-la-estanca-de-alcaniz",
    "kind": "camping",
    "category": 2,
    "zone": "alcaniz",
    "driveMin": 3,
    "ring": 1,
    "score": 4,
    "lat": 41.0670242,
    "lng": -0.1874452,
    "img": "/images/circuits/aragon/camping-la-estanca-de-alcaniz.jpg"
  },
  {
    "name": "Hotel Villa Monter Alcañiz",
    "slug": "hotel-villa-monter-alcaniz",
    "kind": "hotel",
    "category": 3,
    "zone": "alcaniz",
    "driveMin": 6,
    "ring": 1,
    "score": 4.6,
    "lat": 41.0447709,
    "lng": -0.1633251,
    "img": "/images/circuits/aragon/hotel-villa-monter-alcaniz.jpg"
  },
  {
    "name": "Hotel Ciudad de Alcañiz",
    "slug": "hotel-ciudad-de-alcaniz",
    "kind": "hotel",
    "category": 2,
    "zone": "alcaniz",
    "driveMin": 6,
    "ring": 1,
    "score": 4.2,
    "lat": 41.0530556,
    "lng": -0.1536111,
    "img": "/images/circuits/aragon/hotel-ciudad-de-alcaniz.jpg"
  },
  {
    "name": "Torre Alta de Ram",
    "slug": "torre-alta-de-ram",
    "kind": "hotel",
    "category": 3,
    "zone": "alcaniz",
    "driveMin": 7,
    "ring": 1,
    "score": 4.7,
    "lat": 41.0593468,
    "lng": -0.1392629,
    "img": "/images/circuits/aragon/torre-alta-de-ram.jpg"
  },
  {
    "name": "Hostal Los Calatravos",
    "slug": "hostal-los-calatravos",
    "kind": "hotel",
    "category": 1,
    "zone": "alcaniz",
    "driveMin": 8,
    "ring": 1,
    "score": 3.3,
    "lat": 41.055234,
    "lng": -0.132793,
    "img": "/images/circuits/aragon/hostal-los-calatravos.jpg"
  },
  {
    "name": "Casa Telma",
    "slug": "casa-telma",
    "kind": "rental",
    "category": 3,
    "zone": "alcaniz",
    "driveMin": 9,
    "ring": 1,
    "score": 4.9,
    "lat": 41.0276449,
    "lng": -0.1385208,
    "img": "/images/circuits/aragon/casa-telma.jpg"
  }
];
