// AUTO-GENERATED by scripts/gen-circuit-ts.mjs from an Apify scrape.
// Do not edit by hand — re-run the generator to refresh.
import type { CircuitHotel, CircuitZone } from "@/data/circuit-data";

export const balatonZones: CircuitZone[] = [
  {
    "key": "balatonkenese",
    "name": "Balatonkenese",
    "driveMin": 3,
    "ring": 1,
    "count": 1,
    "lat": 47.02703,
    "lng": 18.12886
  },
  {
    "key": "balatonfokajar",
    "name": "Balatonfőkajár",
    "driveMin": 7,
    "ring": 1,
    "count": 2,
    "lat": 47.00663,
    "lng": 18.20056
  },
  {
    "key": "siofok",
    "name": "Siófok",
    "driveMin": 15,
    "ring": 1,
    "count": 1,
    "lat": 46.92762,
    "lng": 18.10312
  },
  {
    "key": "alsoors",
    "name": "Alsóörs",
    "driveMin": 18,
    "ring": 2,
    "count": 1,
    "lat": 46.97608,
    "lng": 17.95688
  },
  {
    "key": "balatonfured",
    "name": "Balatonfüred",
    "driveMin": 26,
    "ring": 2,
    "count": 1,
    "lat": 46.94613,
    "lng": 17.87652
  },
  {
    "key": "zamardi",
    "name": "Zamárdi",
    "driveMin": 29,
    "ring": 2,
    "count": 1,
    "lat": 46.8804,
    "lng": 17.91517
  },
  {
    "key": "balatonakali",
    "name": "Balatonakali",
    "driveMin": 39,
    "ring": 3,
    "count": 1,
    "lat": 46.88106,
    "lng": 17.75426
  },
  {
    "key": "balatonoszod",
    "name": "Balatonőszöd",
    "driveMin": 41,
    "ring": 3,
    "count": 1,
    "lat": 46.81618,
    "lng": 17.79576
  },
  {
    "key": "balatonszemes",
    "name": "Balatonszemes",
    "driveMin": 46,
    "ring": 3,
    "count": 1,
    "lat": 46.80167,
    "lng": 17.7503
  },
  {
    "key": "revfulop",
    "name": "Révfülöp",
    "driveMin": 52,
    "ring": 3,
    "count": 1,
    "lat": 46.82901,
    "lng": 17.64001
  }
];

export const balatonHotels: CircuitHotel[] = [
  {
    "name": "Family Vacation Guesthouse",
    "slug": "family-vacation-guesthouse",
    "kind": "rental",
    "category": 2,
    "zone": "balatonkenese",
    "driveMin": 3,
    "ring": 1,
    "score": null,
    "lat": 47.0270299,
    "lng": 18.128856,
    "img": "/images/circuits/balaton/family-vacation-guesthouse.jpg"
  },
  {
    "name": "Balaton Park Hotel",
    "slug": "balaton-park-hotel",
    "kind": "hotel",
    "category": 3,
    "zone": "balatonfokajar",
    "driveMin": 7,
    "ring": 1,
    "score": 4.7,
    "lat": 47.0108118,
    "lng": 18.2022266,
    "img": "/images/circuits/balaton/balaton-park-hotel.jpg"
  },
  {
    "name": "MotoGP Camping Site",
    "slug": "motogp-camping-site",
    "kind": "camping",
    "category": 2,
    "zone": "balatonfokajar",
    "driveMin": 7,
    "ring": 1,
    "score": 3.8,
    "lat": 47.0024433,
    "lng": 18.1988877,
    "img": "/images/circuits/balaton/motogp-camping-site.jpg"
  },
  {
    "name": "Aranypart Camping & Apartments",
    "slug": "aranypart-camping-apartments",
    "kind": "camping",
    "category": 2,
    "zone": "siofok",
    "driveMin": 15,
    "ring": 1,
    "score": 4.1,
    "lat": 46.9276227,
    "lng": 18.103123,
    "img": "/images/circuits/balaton/aranypart-camping-apartments.jpg"
  },
  {
    "name": "Pelso Camping Alsóörs",
    "slug": "pelso-camping-alsoors",
    "kind": "camping",
    "category": 2,
    "zone": "alsoors",
    "driveMin": 18,
    "ring": 2,
    "score": 4.1,
    "lat": 46.976075,
    "lng": 17.9568848,
    "img": "/images/circuits/balaton/pelso-camping-alsoors.jpg"
  },
  {
    "name": "Balatontourist Füred Camping&Bungalows",
    "slug": "balatontourist-fured-camping-bungalows",
    "kind": "camping",
    "category": 2,
    "zone": "balatonfured",
    "driveMin": 26,
    "ring": 2,
    "score": 3.9,
    "lat": 46.9461294,
    "lng": 17.8765227,
    "img": "/images/circuits/balaton/balatontourist-fured-camping-bungalows.jpg"
  },
  {
    "name": "Camping Mirabella (Ex Car)",
    "slug": "camping-mirabella-ex-car",
    "kind": "camping",
    "category": 2,
    "zone": "zamardi",
    "driveMin": 29,
    "ring": 2,
    "score": 4.4,
    "lat": 46.8803993,
    "lng": 17.915168,
    "img": "/images/circuits/balaton/camping-mirabella-ex-car.jpg"
  },
  {
    "name": "Balatontourist Strand-Holiday Camping",
    "slug": "balatontourist-strand-holiday-camping",
    "kind": "camping",
    "category": 2,
    "zone": "balatonakali",
    "driveMin": 39,
    "ring": 3,
    "score": 4.2,
    "lat": 46.881064,
    "lng": 17.7542595,
    "img": "/images/circuits/balaton/balatontourist-strand-holiday-camping.jpg"
  },
  {
    "name": "Família Camping Balaton",
    "slug": "familia-camping-balaton",
    "kind": "camping",
    "category": 3,
    "zone": "balatonoszod",
    "driveMin": 41,
    "ring": 3,
    "score": 4.8,
    "lat": 46.8161836,
    "lng": 17.7957609,
    "img": "/images/circuits/balaton/familia-camping-balaton.jpg"
  },
  {
    "name": "H&R Mobilcamping",
    "slug": "h-r-mobilcamping",
    "kind": "camping",
    "category": 3,
    "zone": "balatonszemes",
    "driveMin": 46,
    "ring": 3,
    "score": 4.6,
    "lat": 46.8016678,
    "lng": 17.7502999,
    "img": "/images/circuits/balaton/h-r-mobilcamping.jpg"
  },
  {
    "name": "Balatontourist Camping Napfény",
    "slug": "balatontourist-camping-napfeny",
    "kind": "camping",
    "category": 3,
    "zone": "revfulop",
    "driveMin": 52,
    "ring": 3,
    "score": 4.5,
    "lat": 46.829012,
    "lng": 17.6400123,
    "img": "/images/circuits/balaton/balatontourist-camping-napfeny.jpg"
  }
];
