// AUTO-GENERATED by scripts/gen-circuit-ts.mjs from an Apify scrape.
// Do not edit by hand — re-run the generator to refresh.
import type { CircuitHotel, CircuitZone } from "@/data/circuit-data";

export const barcelonaZones: CircuitZone[] = [
  {
    "key": "granollers",
    "name": "Granollers",
    "driveMin": 0,
    "ring": 1,
    "count": 3
  },
  {
    "key": "barcelona",
    "name": "Barcelona",
    "driveMin": 0,
    "ring": 1,
    "count": 9
  },
  {
    "key": "mollet-del-valles",
    "name": "Mollet del Vallès",
    "driveMin": 5,
    "ring": 1,
    "count": 2
  },
  {
    "key": "vallromanes",
    "name": "Vallromanes",
    "driveMin": 6,
    "ring": 1,
    "count": 2
  },
  {
    "key": "alella",
    "name": "Alella",
    "driveMin": 12,
    "ring": 1,
    "count": 1
  },
  {
    "key": "ripollet",
    "name": "Ripollet",
    "driveMin": 14,
    "ring": 1,
    "count": 1
  },
  {
    "key": "circuit-area",
    "name": "Circuit area",
    "driveMin": 15,
    "ring": 1,
    "count": 3
  },
  {
    "key": "barbera-del-valles",
    "name": "Barberà del Vallès",
    "driveMin": 15,
    "ring": 1,
    "count": 1
  },
  {
    "key": "sabadell",
    "name": "Sabadell",
    "driveMin": 15,
    "ring": 1,
    "count": 1
  },
  {
    "key": "mataro",
    "name": "Mataró",
    "driveMin": 17,
    "ring": 2,
    "count": 2
  },
  {
    "key": "centelles",
    "name": "Centelles",
    "driveMin": 22,
    "ring": 2,
    "count": 1
  },
  {
    "key": "arenys-de-mar",
    "name": "Arenys de Mar",
    "driveMin": 30,
    "ring": 2,
    "count": 1
  },
  {
    "key": "canet-de-mar",
    "name": "Canet de Mar",
    "driveMin": 32,
    "ring": 3,
    "count": 1
  },
  {
    "key": "el-prat-de-llobregat",
    "name": "El Prat de Llobregat",
    "driveMin": 36,
    "ring": 3,
    "count": 2
  },
  {
    "key": "santa-susanna",
    "name": "Santa Susanna",
    "driveMin": 44,
    "ring": 3,
    "count": 2
  },
  {
    "key": "castelldefels",
    "name": "Castelldefels",
    "driveMin": 46,
    "ring": 3,
    "count": 1
  },
  {
    "key": "sitges",
    "name": "Sitges",
    "driveMin": 63,
    "ring": 4,
    "count": 2
  },
  {
    "key": "vilanova-i-la-geltru",
    "name": "Vilanova i la Geltrú",
    "driveMin": 68,
    "ring": 4,
    "count": 2
  },
  {
    "key": "sant-jaume-de-frontanya",
    "name": "Sant Jaume de Frontanyà",
    "driveMin": 78,
    "ring": 4,
    "count": 1
  }
];

export const barcelonaHotels: CircuitHotel[] = [
  {
    "name": "ibis Barcelona Montmelo Granollers",
    "slug": "ibis-barcelona-montmelo-granollers",
    "kind": "hotel",
    "category": 2,
    "zone": "granollers",
    "driveMin": 0,
    "ring": 1,
    "score": 4.3,
    "img": "/images/circuits/barcelona/ibis-barcelona-montmelo-granollers.jpg"
  },
  {
    "name": "Holiday Inn Express Barcelona - Montmelo by IHG",
    "slug": "holiday-inn-express-barcelona-montmelo-by-ihg",
    "kind": "hotel",
    "category": 2,
    "zone": "granollers",
    "driveMin": 0,
    "ring": 1,
    "score": 4,
    "img": "/images/circuits/barcelona/holiday-inn-express-barcelona-montmelo-by-ihg.jpg"
  },
  {
    "name": "Overnight Parking F1 Barcelona-Catalunya | Grand Prix F1 Spain | Easy Parking",
    "slug": "overnight-parking-f1-barcelona-catalunya-grand-prix-f1-spain-easy-parking",
    "kind": "camping",
    "category": 2,
    "zone": "barcelona",
    "driveMin": 0,
    "ring": 1,
    "score": null,
    "img": "/images/circuits/barcelona/overnight-parking-f1-barcelona-catalunya-grand-prix-f1-spain-easy-parking.jpg"
  },
  {
    "name": "B&B HOTEL Barcelona Mollet",
    "slug": "b-b-hotel-barcelona-mollet",
    "kind": "hotel",
    "category": 2,
    "zone": "mollet-del-valles",
    "driveMin": 5,
    "ring": 1,
    "score": 4.1,
    "img": "/images/circuits/barcelona/b-b-hotel-barcelona-mollet.jpg"
  },
  {
    "name": "ibis Barcelona Mollet",
    "slug": "ibis-barcelona-mollet",
    "kind": "hotel",
    "category": 2,
    "zone": "mollet-del-valles",
    "driveMin": 6,
    "ring": 1,
    "score": 4.2,
    "img": "/images/circuits/barcelona/ibis-barcelona-mollet.jpg"
  },
  {
    "name": "Hotel Golden Barcelona",
    "slug": "hotel-golden-barcelona",
    "kind": "hotel",
    "category": 2,
    "zone": "vallromanes",
    "driveMin": 6,
    "ring": 1,
    "score": 4,
    "img": "/images/circuits/barcelona/hotel-golden-barcelona.jpg"
  },
  {
    "name": "B&B HOTEL Barcelona Granollers",
    "slug": "b-b-hotel-barcelona-granollers",
    "kind": "hotel",
    "category": 2,
    "zone": "granollers",
    "driveMin": 7,
    "ring": 1,
    "score": 4.2,
    "img": "/images/circuits/barcelona/b-b-hotel-barcelona-granollers.jpg"
  },
  {
    "name": "El Vedado Càmping",
    "slug": "el-vedado-camping",
    "kind": "camping",
    "category": 1,
    "zone": "vallromanes",
    "driveMin": 7,
    "ring": 1,
    "score": 3.4,
    "img": "/images/circuits/barcelona/el-vedado-camping.jpg"
  },
  {
    "name": "Hotel Arrey Alella",
    "slug": "hotel-arrey-alella",
    "kind": "hotel",
    "category": 2,
    "zone": "alella",
    "driveMin": 12,
    "ring": 1,
    "score": 4.2,
    "img": "/images/circuits/barcelona/hotel-arrey-alella.jpg"
  },
  {
    "name": "ibis Barcelona Ripollet",
    "slug": "ibis-barcelona-ripollet",
    "kind": "hotel",
    "category": 2,
    "zone": "ripollet",
    "driveMin": 14,
    "ring": 1,
    "score": 4.1,
    "img": "/images/circuits/barcelona/ibis-barcelona-ripollet.jpg"
  },
  {
    "name": "ibis Barcelona Santa Coloma",
    "slug": "ibis-barcelona-santa-coloma",
    "kind": "hotel",
    "category": 2,
    "zone": "circuit-area",
    "driveMin": 15,
    "ring": 1,
    "score": 4.2,
    "img": "/images/circuits/barcelona/ibis-barcelona-santa-coloma.jpg"
  },
  {
    "name": "Hotel Eurostars Executive",
    "slug": "hotel-eurostars-executive",
    "kind": "hotel",
    "category": 2,
    "zone": "barbera-del-valles",
    "driveMin": 15,
    "ring": 1,
    "score": 4.1,
    "img": "/images/circuits/barcelona/hotel-eurostars-executive.jpg"
  },
  {
    "name": "Hotel Urpí",
    "slug": "hotel-urpi",
    "kind": "hotel",
    "category": 2,
    "zone": "sabadell",
    "driveMin": 15,
    "ring": 1,
    "score": 3.9,
    "img": "/images/circuits/barcelona/hotel-urpi.jpg"
  },
  {
    "name": "B&B HOTEL Mataró",
    "slug": "b-b-hotel-mataro",
    "kind": "hotel",
    "category": 2,
    "zone": "mataro",
    "driveMin": 17,
    "ring": 2,
    "score": 4.1,
    "img": "/images/circuits/barcelona/b-b-hotel-mataro.jpg"
  },
  {
    "name": "Acta Laumon",
    "slug": "acta-laumon",
    "kind": "hotel",
    "category": 2,
    "zone": "barcelona",
    "driveMin": 20,
    "ring": 2,
    "score": 4.2,
    "img": "/images/circuits/barcelona/acta-laumon.jpg"
  },
  {
    "name": "Hilton Diagonal Mar Barcelona",
    "slug": "hilton-diagonal-mar-barcelona",
    "kind": "hotel",
    "category": 2,
    "zone": "barcelona",
    "driveMin": 21,
    "ring": 2,
    "score": 4.3,
    "img": "/images/circuits/barcelona/hilton-diagonal-mar-barcelona.jpg"
  },
  {
    "name": "Hotel Barcelona Princess",
    "slug": "hotel-barcelona-princess",
    "kind": "hotel",
    "category": 2,
    "zone": "barcelona",
    "driveMin": 21,
    "ring": 2,
    "score": 4.2,
    "img": "/images/circuits/barcelona/hotel-barcelona-princess.jpg"
  },
  {
    "name": "Hotel Barcelona Condal Mar Affiliated by Meliá",
    "slug": "hotel-barcelona-condal-mar-affiliated-by-melia",
    "kind": "hotel",
    "category": 2,
    "zone": "barcelona",
    "driveMin": 21,
    "ring": 2,
    "score": 4.1,
    "img": "/images/circuits/barcelona/hotel-barcelona-condal-mar-affiliated-by-melia.jpg"
  },
  {
    "name": "Càmping BARCELONA",
    "slug": "camping-barcelona",
    "kind": "camping",
    "category": 2,
    "zone": "mataro",
    "driveMin": 22,
    "ring": 2,
    "score": 4.2,
    "img": "/images/circuits/barcelona/camping-barcelona.jpg"
  },
  {
    "name": "Càmping L'Illa",
    "slug": "camping-l-illa",
    "kind": "camping",
    "category": 1,
    "zone": "centelles",
    "driveMin": 22,
    "ring": 2,
    "score": 3.7,
    "img": "/images/circuits/barcelona/camping-l-illa.jpg"
  },
  {
    "name": "Guest House in Barcelona, Spain",
    "slug": "guest-house-in-barcelona-spain",
    "kind": "rental",
    "category": 3,
    "zone": "barcelona",
    "driveMin": 24,
    "ring": 2,
    "score": 5,
    "img": "/images/circuits/barcelona/guest-house-in-barcelona-spain.jpg"
  },
  {
    "name": "Grums Hotel&Spa",
    "slug": "grums-hotel-spa",
    "kind": "hotel",
    "category": 2,
    "zone": "barcelona",
    "driveMin": 26,
    "ring": 2,
    "score": 4.1,
    "img": "/images/circuits/barcelona/grums-hotel-spa.jpg"
  },
  {
    "name": "Càmping El Toro Azul",
    "slug": "camping-el-toro-azul",
    "kind": "camping",
    "category": 2,
    "zone": "arenys-de-mar",
    "driveMin": 30,
    "ring": 2,
    "score": 3.9,
    "img": "/images/circuits/barcelona/camping-el-toro-azul.jpg"
  },
  {
    "name": "Càmping Victòria",
    "slug": "camping-victoria",
    "kind": "camping",
    "category": 2,
    "zone": "barcelona",
    "driveMin": 30,
    "ring": 2,
    "score": 3.8,
    "img": "/images/circuits/barcelona/camping-victoria.jpg"
  },
  {
    "name": "Camping Globo Barcelona",
    "slug": "camping-globo-barcelona",
    "kind": "camping",
    "category": 2,
    "zone": "canet-de-mar",
    "driveMin": 32,
    "ring": 3,
    "score": 4.4,
    "img": "/images/circuits/barcelona/camping-globo-barcelona.jpg"
  },
  {
    "name": "Airhostel BCN",
    "slug": "airhostel-bcn",
    "kind": "hotel",
    "category": 2,
    "zone": "el-prat-de-llobregat",
    "driveMin": 36,
    "ring": 3,
    "score": 4.3,
    "img": "/images/circuits/barcelona/airhostel-bcn.jpg"
  },
  {
    "name": "Alberg Centre Esplai",
    "slug": "alberg-centre-esplai",
    "kind": "hotel",
    "category": 1,
    "zone": "el-prat-de-llobregat",
    "driveMin": 37,
    "ring": 3,
    "score": 3.7,
    "img": "/images/circuits/barcelona/alberg-centre-esplai.jpg"
  },
  {
    "name": "Càmping Oasis",
    "slug": "camping-oasis",
    "kind": "camping",
    "category": 3,
    "zone": "santa-susanna",
    "driveMin": 44,
    "ring": 3,
    "score": 4.5,
    "img": "/images/circuits/barcelona/camping-oasis.jpg"
  },
  {
    "name": "Camping 3 Estrelles",
    "slug": "camping-3-estrelles",
    "kind": "camping",
    "category": 2,
    "zone": "circuit-area",
    "driveMin": 44,
    "ring": 3,
    "score": 3.8,
    "img": "/images/circuits/barcelona/camping-3-estrelles.jpg"
  },
  {
    "name": "Càmping Bon Repòs",
    "slug": "camping-bon-repos",
    "kind": "camping",
    "category": 2,
    "zone": "santa-susanna",
    "driveMin": 45,
    "ring": 3,
    "score": 4.1,
    "img": "/images/circuits/barcelona/camping-bon-repos.jpg"
  },
  {
    "name": "Camping Estrella de Mar",
    "slug": "camping-estrella-de-mar",
    "kind": "camping",
    "category": 1,
    "zone": "castelldefels",
    "driveMin": 46,
    "ring": 3,
    "score": 3.6,
    "img": "/images/circuits/barcelona/camping-estrella-de-mar.jpg"
  },
  {
    "name": "Càmping El Pont",
    "slug": "camping-el-pont",
    "kind": "camping",
    "category": 1,
    "zone": "barcelona",
    "driveMin": 48,
    "ring": 3,
    "score": 3.6,
    "img": "/images/circuits/barcelona/camping-el-pont.jpg"
  },
  {
    "name": "HolaCamp Sitges Garrofer",
    "slug": "holacamp-sitges-garrofer",
    "kind": "camping",
    "category": 2,
    "zone": "sitges",
    "driveMin": 63,
    "ring": 4,
    "score": 4,
    "img": "/images/circuits/barcelona/holacamp-sitges-garrofer.jpg"
  },
  {
    "name": "HolaCamp Sitges Relax",
    "slug": "holacamp-sitges-relax",
    "kind": "camping",
    "category": 2,
    "zone": "sitges",
    "driveMin": 63,
    "ring": 4,
    "score": 4,
    "img": "/images/circuits/barcelona/holacamp-sitges-relax.jpg"
  },
  {
    "name": "Mas Alegria",
    "slug": "mas-alegria",
    "kind": "camping",
    "category": 3,
    "zone": "vilanova-i-la-geltru",
    "driveMin": 68,
    "ring": 4,
    "score": 4.8,
    "img": "/images/circuits/barcelona/mas-alegria.jpg"
  },
  {
    "name": "Càmping Vilademàger S.L",
    "slug": "camping-vilademager-s-l",
    "kind": "camping",
    "category": 3,
    "zone": "circuit-area",
    "driveMin": 69,
    "ring": 4,
    "score": 4.6,
    "img": "/images/circuits/barcelona/camping-vilademager-s-l.jpg"
  },
  {
    "name": "Camping El Racó del Mar",
    "slug": "camping-el-raco-del-mar",
    "kind": "camping",
    "category": 1,
    "zone": "vilanova-i-la-geltru",
    "driveMin": 70,
    "ring": 4,
    "score": 3.6,
    "img": "/images/circuits/barcelona/camping-el-raco-del-mar.jpg"
  },
  {
    "name": "Càmping Campalans",
    "slug": "camping-campalans",
    "kind": "camping",
    "category": 2,
    "zone": "sant-jaume-de-frontanya",
    "driveMin": 78,
    "ring": 4,
    "score": 4.1,
    "img": "/images/circuits/barcelona/camping-campalans.jpg"
  }
];
