// AUTO-GENERATED by scripts/gen-circuit-ts.mjs from an Apify scrape.
// Do not edit by hand — re-run the generator to refresh.
import type { CircuitHotel, CircuitZone } from "@/data/circuit-data";

export const hungaroringZones: CircuitZone[] = [
  {
    "key": "mogyorod",
    "name": "Mogyoród",
    "driveMin": 0,
    "ring": 1,
    "count": 4,
    "lat": 47.5833,
    "lng": 19.24472
  },
  {
    "key": "kerepes",
    "name": "Kerepes",
    "driveMin": 0,
    "ring": 1,
    "count": 2,
    "lat": 47.5766,
    "lng": 19.26239
  },
  {
    "key": "fot",
    "name": "Fót",
    "driveMin": 8,
    "ring": 1,
    "count": 1,
    "lat": 47.62267,
    "lng": 19.18788
  },
  {
    "key": "nagytarcsa",
    "name": "Nagytarcsa",
    "driveMin": 8,
    "ring": 1,
    "count": 1,
    "lat": 47.51904,
    "lng": 19.26183
  },
  {
    "key": "godollo",
    "name": "Gödöllő",
    "driveMin": 9,
    "ring": 1,
    "count": 3,
    "lat": 47.60011,
    "lng": 19.35918
  },
  {
    "key": "veresegyhaz",
    "name": "Veresegyház",
    "driveMin": 10,
    "ring": 1,
    "count": 2,
    "lat": 47.65531,
    "lng": 19.27768
  },
  {
    "key": "budapest",
    "name": "Budapest",
    "driveMin": 10,
    "ring": 1,
    "count": 5,
    "lat": 47.53455,
    "lng": 19.09326
  },
  {
    "key": "vecses",
    "name": "Vecsés",
    "driveMin": 22,
    "ring": 2,
    "count": 1,
    "lat": 47.40494,
    "lng": 19.23756
  }
];

export const hungaroringHotels: CircuitHotel[] = [
  {
    "name": "Camping II",
    "slug": "camping-ii",
    "kind": "camping",
    "category": 1,
    "zone": "mogyorod",
    "driveMin": 0,
    "ring": 1,
    "score": 3.2,
    "lat": 47.5779865,
    "lng": 19.2438839,
    "img": "/images/circuits/hungaroring/camping-ii.jpg"
  },
  {
    "name": "Small House Apartment",
    "slug": "small-house-apartment",
    "kind": "hotel",
    "category": 3,
    "zone": "kerepes",
    "driveMin": 0,
    "ring": 1,
    "score": 5,
    "lat": 47.575952,
    "lng": 19.2646346,
    "img": "/images/circuits/hungaroring/small-house-apartment.jpg"
  },
  {
    "name": "Royal PRing Camping",
    "slug": "royal-pring-camping",
    "kind": "camping",
    "category": 2,
    "zone": "kerepes",
    "driveMin": 0,
    "ring": 1,
    "score": 4.4,
    "lat": 47.577245,
    "lng": 19.2601456,
    "img": "/images/circuits/hungaroring/royal-pring-camping.jpg"
  },
  {
    "name": "Zengő camping",
    "slug": "zengo-camping",
    "kind": "camping",
    "category": 2,
    "zone": "mogyorod",
    "driveMin": 0,
    "ring": 1,
    "score": 4.2,
    "lat": 47.575512,
    "lng": 19.2537292,
    "img": "/images/circuits/hungaroring/zengo-camping.jpg"
  },
  {
    "name": "Gold Panoráma Camping",
    "slug": "gold-panorama-camping",
    "kind": "camping",
    "category": 2,
    "zone": "mogyorod",
    "driveMin": 0,
    "ring": 1,
    "score": 4,
    "lat": 47.5822199,
    "lng": 19.2404618,
    "img": "/images/circuits/hungaroring/gold-panorama-camping.jpg"
  },
  {
    "name": "Kamarás Klastrom House",
    "slug": "kamaras-klastrom-house",
    "kind": "rental",
    "category": 3,
    "zone": "mogyorod",
    "driveMin": 3,
    "ring": 1,
    "score": 4.9,
    "lat": 47.5974998,
    "lng": 19.2408123,
    "img": "/images/circuits/hungaroring/kamaras-klastrom-house.jpg"
  },
  {
    "name": "Hostel Fót",
    "slug": "hostel-fot",
    "kind": "rental",
    "category": 3,
    "zone": "fot",
    "driveMin": 8,
    "ring": 1,
    "score": 4.7,
    "lat": 47.6226711,
    "lng": 19.1878772,
    "img": "/images/circuits/hungaroring/hostel-fot.jpg"
  },
  {
    "name": "Szilas Park Motel",
    "slug": "szilas-park-motel",
    "kind": "hotel",
    "category": 2,
    "zone": "nagytarcsa",
    "driveMin": 8,
    "ring": 1,
    "score": 4.2,
    "lat": 47.5190428,
    "lng": 19.2618252,
    "img": "/images/circuits/hungaroring/szilas-park-motel.jpg"
  },
  {
    "name": "Hotel Queen Elizabeth",
    "slug": "hotel-queen-elizabeth",
    "kind": "hotel",
    "category": 3,
    "zone": "godollo",
    "driveMin": 9,
    "ring": 1,
    "score": 4.5,
    "lat": 47.5989147,
    "lng": 19.3474277,
    "img": "/images/circuits/hungaroring/hotel-queen-elizabeth.jpg"
  },
  {
    "name": "Villa Oliver Gödöllő",
    "slug": "villa-oliver-godollo",
    "kind": "rental",
    "category": 2,
    "zone": "godollo",
    "driveMin": 9,
    "ring": 1,
    "score": 4.1,
    "lat": 47.601502,
    "lng": 19.343785,
    "img": "/images/circuits/hungaroring/villa-oliver-godollo.jpg"
  },
  {
    "name": "Veres Motel",
    "slug": "veres-motel",
    "kind": "rental",
    "category": 3,
    "zone": "veresegyhaz",
    "driveMin": 10,
    "ring": 1,
    "score": 4.7,
    "lat": 47.6569236,
    "lng": 19.2658824,
    "img": "/images/circuits/hungaroring/veres-motel.jpg"
  },
  {
    "name": "Libra Hotel",
    "slug": "libra-hotel",
    "kind": "hotel",
    "category": 3,
    "zone": "veresegyhaz",
    "driveMin": 10,
    "ring": 1,
    "score": 4.7,
    "lat": 47.6536881,
    "lng": 19.2894719,
    "img": "/images/circuits/hungaroring/libra-hotel.jpg"
  },
  {
    "name": "Hotel City Palace",
    "slug": "hotel-city-palace",
    "kind": "hotel",
    "category": 2,
    "zone": "budapest",
    "driveMin": 10,
    "ring": 1,
    "score": 4.4,
    "lat": 47.5629781,
    "lng": 19.1249212,
    "img": "/images/circuits/hungaroring/hotel-city-palace.jpg"
  },
  {
    "name": "Camping Arena Budapest",
    "slug": "camping-arena-budapest",
    "kind": "camping",
    "category": 3,
    "zone": "budapest",
    "driveMin": 13,
    "ring": 1,
    "score": 4.7,
    "lat": 47.504162,
    "lng": 19.158384,
    "img": "/images/circuits/hungaroring/camping-arena-budapest.jpg"
  },
  {
    "name": "Aquaworld Resort Budapest",
    "slug": "aquaworld-resort-budapest",
    "kind": "hotel",
    "category": 3,
    "zone": "budapest",
    "driveMin": 13,
    "ring": 1,
    "score": 4.5,
    "lat": 47.6010861,
    "lng": 19.112265,
    "img": "/images/circuits/hungaroring/aquaworld-resort-budapest.jpg"
  },
  {
    "name": "Árnyas Panzió és Rendezvényközpont",
    "slug": "arnyas-panzio-es-rendezvenykozpont",
    "kind": "hotel",
    "category": 2,
    "zone": "godollo",
    "driveMin": 13,
    "ring": 1,
    "score": 4.4,
    "lat": 47.5999042,
    "lng": 19.3863374,
    "img": "/images/circuits/hungaroring/arnyas-panzio-es-rendezvenykozpont.jpg"
  },
  {
    "name": "Buda Castle Hotel",
    "slug": "buda-castle-hotel",
    "kind": "hotel",
    "category": 3,
    "zone": "budapest",
    "driveMin": 21,
    "ring": 2,
    "score": 4.6,
    "lat": 47.5019352,
    "lng": 19.0311638,
    "img": "/images/circuits/hungaroring/buda-castle-hotel.jpg"
  },
  {
    "name": "Park Plaza Budapest",
    "slug": "park-plaza-budapest",
    "kind": "hotel",
    "category": 2,
    "zone": "budapest",
    "driveMin": 21,
    "ring": 2,
    "score": 4.3,
    "lat": 47.5025948,
    "lng": 19.0395694,
    "img": "/images/circuits/hungaroring/park-plaza-budapest.jpg"
  },
  {
    "name": "NOA Panzió",
    "slug": "noa-panzio",
    "kind": "hotel",
    "category": 3,
    "zone": "vecses",
    "driveMin": 22,
    "ring": 2,
    "score": 4.9,
    "lat": 47.4049375,
    "lng": 19.2375625,
    "img": "/images/circuits/hungaroring/noa-panzio.jpg"
  }
];
