// AUTO-GENERATED by scripts/gen-circuit-ts.mjs from an Apify scrape.
// Do not edit by hand — re-run the generator to refresh.
import type { CircuitHotel, CircuitZone } from "@/data/circuit-data";

export const monacoZones: CircuitZone[] = [
  {
    "key": "monaco",
    "name": "Monaco",
    "driveMin": 0,
    "ring": 1,
    "count": 14
  },
  {
    "key": "cap-d-ail",
    "name": "Cap-d'Ail",
    "driveMin": 0,
    "ring": 1,
    "count": 2
  },
  {
    "key": "gorbio",
    "name": "Gorbio",
    "driveMin": 7,
    "ring": 1,
    "count": 1
  },
  {
    "key": "peillon",
    "name": "Peillon",
    "driveMin": 7,
    "ring": 1,
    "count": 1
  },
  {
    "key": "menton",
    "name": "Menton",
    "driveMin": 9,
    "ring": 1,
    "count": 1
  },
  {
    "key": "contes",
    "name": "Contes",
    "driveMin": 13,
    "ring": 1,
    "count": 1
  },
  {
    "key": "ventimiglia",
    "name": "Ventimiglia",
    "driveMin": 15,
    "ring": 1,
    "count": 1
  }
];

export const monacoHotels: CircuitHotel[] = [
  {
    "name": "Boutique Hotel Miramar - Monte Carlo",
    "slug": "boutique-hotel-miramar-monte-carlo",
    "kind": "hotel",
    "category": 3,
    "zone": "monaco",
    "driveMin": 0,
    "ring": 1,
    "score": 4.5,
    "img": "/images/circuits/monaco/boutique-hotel-miramar-monte-carlo.jpg"
  },
  {
    "name": "Port Palace Hôtel",
    "slug": "port-palace-hotel",
    "kind": "hotel",
    "category": 3,
    "zone": "monaco",
    "driveMin": 0,
    "ring": 1,
    "score": 4.5,
    "img": "/images/circuits/monaco/port-palace-hotel.jpg"
  },
  {
    "name": "Novotel Monte Carlo",
    "slug": "novotel-monte-carlo",
    "kind": "hotel",
    "category": 2,
    "zone": "monaco",
    "driveMin": 0,
    "ring": 1,
    "score": 4.4,
    "img": "/images/circuits/monaco/novotel-monte-carlo.jpg"
  },
  {
    "name": "Hôtel de France",
    "slug": "hotel-de-france",
    "kind": "hotel",
    "category": 2,
    "zone": "monaco",
    "driveMin": 0,
    "ring": 1,
    "score": 4.1,
    "img": "/images/circuits/monaco/hotel-de-france.jpg"
  },
  {
    "name": "Hotel Ambassador Monaco",
    "slug": "hotel-ambassador-monaco",
    "kind": "hotel",
    "category": 1,
    "zone": "monaco",
    "driveMin": 0,
    "ring": 1,
    "score": 3.6,
    "img": "/images/circuits/monaco/hotel-ambassador-monaco.jpg"
  },
  {
    "name": "Hotel de Paris Monte-Carlo",
    "slug": "hotel-de-paris-monte-carlo",
    "kind": "hotel",
    "category": 3,
    "zone": "monaco",
    "driveMin": 0,
    "ring": 1,
    "score": 4.7,
    "img": "/images/circuits/monaco/hotel-de-paris-monte-carlo.jpg"
  },
  {
    "name": "Hôtel Hermitage Monte-Carlo",
    "slug": "hotel-hermitage-monte-carlo",
    "kind": "hotel",
    "category": 3,
    "zone": "monaco",
    "driveMin": 0,
    "ring": 1,
    "score": 4.7,
    "img": "/images/circuits/monaco/hotel-hermitage-monte-carlo.jpg"
  },
  {
    "name": "Hotel Metropole, Monte Carlo",
    "slug": "hotel-metropole-monte-carlo",
    "kind": "hotel",
    "category": 3,
    "zone": "monaco",
    "driveMin": 0,
    "ring": 1,
    "score": 4.6,
    "img": "/images/circuits/monaco/hotel-metropole-monte-carlo.jpg"
  },
  {
    "name": "Fairmont Monte Carlo",
    "slug": "fairmont-monte-carlo",
    "kind": "hotel",
    "category": 3,
    "zone": "monaco",
    "driveMin": 0,
    "ring": 1,
    "score": 4.5,
    "img": "/images/circuits/monaco/fairmont-monte-carlo.jpg"
  },
  {
    "name": "Columbus Hotel Monte-Carlo, Curio Collection by Hilton",
    "slug": "columbus-hotel-monte-carlo-curio-collection-by-hilton",
    "kind": "hotel",
    "category": 2,
    "zone": "monaco",
    "driveMin": 0,
    "ring": 1,
    "score": 4.4,
    "img": "/images/circuits/monaco/columbus-hotel-monte-carlo-curio-collection-by-hilton.jpg"
  },
  {
    "name": "Riviera Marriott Hotel La Porte de Monaco",
    "slug": "riviera-marriott-hotel-la-porte-de-monaco",
    "kind": "hotel",
    "category": 2,
    "zone": "cap-d-ail",
    "driveMin": 0,
    "ring": 1,
    "score": 4.3,
    "img": "/images/circuits/monaco/riviera-marriott-hotel-la-porte-de-monaco.jpg"
  },
  {
    "name": "Le Quai Des Princes",
    "slug": "le-quai-des-princes",
    "kind": "hotel",
    "category": 2,
    "zone": "cap-d-ail",
    "driveMin": 0,
    "ring": 1,
    "score": 3.9,
    "img": "/images/circuits/monaco/le-quai-des-princes.jpg"
  },
  {
    "name": "LA VOGLIA MATTA",
    "slug": "la-voglia-matta",
    "kind": "rental",
    "category": 1,
    "zone": "monaco",
    "driveMin": 0,
    "ring": 1,
    "score": 3,
    "img": "/images/circuits/monaco/la-voglia-matta.jpg"
  },
  {
    "name": "Quality Hotel Menton Mediterranée",
    "slug": "quality-hotel-menton-mediterranee",
    "kind": "hotel",
    "category": 2,
    "zone": "monaco",
    "driveMin": 0,
    "ring": 1,
    "score": null,
    "img": "/images/circuits/monaco/quality-hotel-menton-mediterranee.jpg"
  },
  {
    "name": "Monte-Carlo Bay Hotel & Resort",
    "slug": "monte-carlo-bay-hotel-resort",
    "kind": "hotel",
    "category": 3,
    "zone": "monaco",
    "driveMin": 3,
    "ring": 1,
    "score": 4.6,
    "img": "/images/circuits/monaco/monte-carlo-bay-hotel-resort.jpg"
  },
  {
    "name": "Le Méridien Beach Plaza",
    "slug": "le-meridien-beach-plaza",
    "kind": "hotel",
    "category": 2,
    "zone": "monaco",
    "driveMin": 3,
    "ring": 1,
    "score": 4.4,
    "img": "/images/circuits/monaco/le-meridien-beach-plaza.jpg"
  },
  {
    "name": "Camping la giandolla",
    "slug": "camping-la-giandolla",
    "kind": "camping",
    "category": 3,
    "zone": "gorbio",
    "driveMin": 7,
    "ring": 1,
    "score": 4.5,
    "img": "/images/circuits/monaco/camping-la-giandolla.jpg"
  },
  {
    "name": "Camping de La Laune",
    "slug": "camping-de-la-laune",
    "kind": "camping",
    "category": 2,
    "zone": "peillon",
    "driveMin": 7,
    "ring": 1,
    "score": 4.2,
    "img": "/images/circuits/monaco/camping-de-la-laune.jpg"
  },
  {
    "name": "Camping Parc Saint Michel",
    "slug": "camping-parc-saint-michel",
    "kind": "camping",
    "category": 1,
    "zone": "menton",
    "driveMin": 9,
    "ring": 1,
    "score": 3.4,
    "img": "/images/circuits/monaco/camping-parc-saint-michel.jpg"
  },
  {
    "name": "Camping La Ferme Riola",
    "slug": "camping-la-ferme-riola",
    "kind": "camping",
    "category": 3,
    "zone": "contes",
    "driveMin": 13,
    "ring": 1,
    "score": 4.8,
    "img": "/images/circuits/monaco/camping-la-ferme-riola.jpg"
  },
  {
    "name": "Camping Por La Mar",
    "slug": "camping-por-la-mar",
    "kind": "camping",
    "category": 2,
    "zone": "ventimiglia",
    "driveMin": 15,
    "ring": 1,
    "score": 4.3,
    "img": "/images/circuits/monaco/camping-por-la-mar.jpg"
  }
];
