// AUTO-GENERATED by scripts/gen-circuit-ts.mjs from an Apify scrape.
// Do not edit by hand — re-run the generator to refresh.
import type { CircuitHotel, CircuitZone } from "@/data/circuit-data";

export const monzaZones: CircuitZone[] = [
  {
    "key": "lissone",
    "name": "Lissone",
    "driveMin": 3,
    "ring": 1,
    "count": 4
  },
  {
    "key": "monza",
    "name": "Monza",
    "driveMin": 3,
    "ring": 1,
    "count": 13
  },
  {
    "key": "arcore",
    "name": "Arcore",
    "driveMin": 3,
    "ring": 1,
    "count": 3
  },
  {
    "key": "triuggio",
    "name": "Triuggio",
    "driveMin": 5,
    "ring": 1,
    "count": 1
  },
  {
    "key": "agrate-brianza",
    "name": "Agrate Brianza",
    "driveMin": 7,
    "ring": 1,
    "count": 1
  },
  {
    "key": "pl-industriale-via-manzoni",
    "name": "Pl Industriale Via Manzoni",
    "driveMin": 9,
    "ring": 1,
    "count": 1
  },
  {
    "key": "verano-brianza",
    "name": "Verano Brianza",
    "driveMin": 10,
    "ring": 1,
    "count": 1
  }
];

export const monzaHotels: CircuitHotel[] = [
  {
    "name": "AL SUITE",
    "slug": "al-suite",
    "kind": "rental",
    "category": 3,
    "zone": "lissone",
    "driveMin": 3,
    "ring": 1,
    "score": 5,
    "img": "/images/circuits/monza/al-suite.jpg"
  },
  {
    "name": "Il Giardino degli Ulivi",
    "slug": "il-giardino-degli-ulivi",
    "kind": "rental",
    "category": 3,
    "zone": "lissone",
    "driveMin": 3,
    "ring": 1,
    "score": 5,
    "img": "/images/circuits/monza/il-giardino-degli-ulivi.jpg"
  },
  {
    "name": "Hotel de la Ville",
    "slug": "hotel-de-la-ville",
    "kind": "hotel",
    "category": 3,
    "zone": "monza",
    "driveMin": 3,
    "ring": 1,
    "score": 4.7,
    "img": "/images/circuits/monza/hotel-de-la-ville.jpg"
  },
  {
    "name": "Carro Rooms",
    "slug": "carro-rooms",
    "kind": "rental",
    "category": 2,
    "zone": "monza",
    "driveMin": 3,
    "ring": 1,
    "score": 4.2,
    "img": "/images/circuits/monza/carro-rooms.jpg"
  },
  {
    "name": "Helios Hotel",
    "slug": "helios-hotel",
    "kind": "hotel",
    "category": 2,
    "zone": "monza",
    "driveMin": 3,
    "ring": 1,
    "score": 4.1,
    "img": "/images/circuits/monza/helios-hotel.jpg"
  },
  {
    "name": "Antica Trattoria Dell'Uva",
    "slug": "antica-trattoria-dell-uva",
    "kind": "hotel",
    "category": 2,
    "zone": "monza",
    "driveMin": 3,
    "ring": 1,
    "score": 4.1,
    "img": "/images/circuits/monza/antica-trattoria-dell-uva.jpg"
  },
  {
    "name": "Residence Cascina San Giovanni",
    "slug": "residence-cascina-san-giovanni",
    "kind": "hotel",
    "category": 2,
    "zone": "arcore",
    "driveMin": 3,
    "ring": 1,
    "score": 3.9,
    "img": "/images/circuits/monza/residence-cascina-san-giovanni.jpg"
  },
  {
    "name": "Mosca",
    "slug": "mosca",
    "kind": "hotel",
    "category": 1,
    "zone": "monza",
    "driveMin": 3,
    "ring": 1,
    "score": 3.2,
    "img": "/images/circuits/monza/mosca.jpg"
  },
  {
    "name": "Duomo Guest House",
    "slug": "duomo-guest-house",
    "kind": "rental",
    "category": 3,
    "zone": "monza",
    "driveMin": 5,
    "ring": 1,
    "score": 5,
    "img": "/images/circuits/monza/duomo-guest-house.jpg"
  },
  {
    "name": "Villa Tosati",
    "slug": "villa-tosati",
    "kind": "rental",
    "category": 3,
    "zone": "monza",
    "driveMin": 5,
    "ring": 1,
    "score": 5,
    "img": "/images/circuits/monza/villa-tosati.jpg"
  },
  {
    "name": "Residence Oasi di Monza",
    "slug": "residence-oasi-di-monza",
    "kind": "hotel",
    "category": 2,
    "zone": "monza",
    "driveMin": 5,
    "ring": 1,
    "score": 4.4,
    "img": "/images/circuits/monza/residence-oasi-di-monza.jpg"
  },
  {
    "name": "BEST WESTERN Hotel Borgolecco",
    "slug": "best-western-hotel-borgolecco",
    "kind": "hotel",
    "category": 2,
    "zone": "arcore",
    "driveMin": 5,
    "ring": 1,
    "score": 4.4,
    "img": "/images/circuits/monza/best-western-hotel-borgolecco.jpg"
  },
  {
    "name": "The Regency Hotel",
    "slug": "the-regency-hotel",
    "kind": "hotel",
    "category": 2,
    "zone": "lissone",
    "driveMin": 5,
    "ring": 1,
    "score": 4.3,
    "img": "/images/circuits/monza/the-regency-hotel.jpg"
  },
  {
    "name": "Albergo Ristorante Sant'Eustorgio",
    "slug": "albergo-ristorante-sant-eustorgio",
    "kind": "hotel",
    "category": 2,
    "zone": "arcore",
    "driveMin": 5,
    "ring": 1,
    "score": 4.2,
    "img": "/images/circuits/monza/albergo-ristorante-sant-eustorgio.jpg"
  },
  {
    "name": "Hotel Fossati Di Fossati Antonio Snc",
    "slug": "hotel-fossati-di-fossati-antonio-snc",
    "kind": "hotel",
    "category": 2,
    "zone": "triuggio",
    "driveMin": 5,
    "ring": 1,
    "score": 4.2,
    "img": "/images/circuits/monza/hotel-fossati-di-fossati-antonio-snc.jpg"
  },
  {
    "name": "AS Hotel Monza",
    "slug": "as-hotel-monza",
    "kind": "hotel",
    "category": 2,
    "zone": "monza",
    "driveMin": 5,
    "ring": 1,
    "score": 4.1,
    "img": "/images/circuits/monza/as-hotel-monza.jpg"
  },
  {
    "name": "Hotel Royal Falcone",
    "slug": "hotel-royal-falcone",
    "kind": "hotel",
    "category": 2,
    "zone": "monza",
    "driveMin": 5,
    "ring": 1,
    "score": 4.1,
    "img": "/images/circuits/monza/hotel-royal-falcone.jpg"
  },
  {
    "name": "NINE HOTEL",
    "slug": "nine-hotel",
    "kind": "hotel",
    "category": 2,
    "zone": "monza",
    "driveMin": 5,
    "ring": 1,
    "score": 4,
    "img": "/images/circuits/monza/nine-hotel.jpg"
  },
  {
    "name": "Hotel Karol",
    "slug": "hotel-karol",
    "kind": "hotel",
    "category": 2,
    "zone": "monza",
    "driveMin": 5,
    "ring": 1,
    "score": 3.9,
    "img": "/images/circuits/monza/hotel-karol.jpg"
  },
  {
    "name": "Hotel Re",
    "slug": "hotel-re",
    "kind": "hotel",
    "category": 1,
    "zone": "lissone",
    "driveMin": 5,
    "ring": 1,
    "score": 3.7,
    "img": "/images/circuits/monza/hotel-re.jpg"
  },
  {
    "name": "Monza guest house Casa30",
    "slug": "monza-guest-house-casa30",
    "kind": "rental",
    "category": 3,
    "zone": "monza",
    "driveMin": 6,
    "ring": 1,
    "score": 5,
    "img": "/images/circuits/monza/monza-guest-house-casa30.jpg"
  },
  {
    "name": "Mercure Milano Agrate Brianza",
    "slug": "mercure-milano-agrate-brianza",
    "kind": "hotel",
    "category": 2,
    "zone": "agrate-brianza",
    "driveMin": 7,
    "ring": 1,
    "score": 4.3,
    "img": "/images/circuits/monza/mercure-milano-agrate-brianza.jpg"
  },
  {
    "name": "Parcheggio camion",
    "slug": "parcheggio-camion",
    "kind": "camping",
    "category": 3,
    "zone": "pl-industriale-via-manzoni",
    "driveMin": 9,
    "ring": 1,
    "score": 5,
    "img": "/images/circuits/monza/parcheggio-camion.jpg"
  },
  {
    "name": "Ospedale vecchio monza",
    "slug": "ospedale-vecchio-monza",
    "kind": "camping",
    "category": 2,
    "zone": "verano-brianza",
    "driveMin": 10,
    "ring": 1,
    "score": null,
    "img": "/images/circuits/monza/ospedale-vecchio-monza.jpg"
  }
];
