// AUTO-GENERATED by scripts/gen-circuit-ts.mjs from an Apify scrape.
// Do not edit by hand — re-run the generator to refresh.
import type { CircuitHotel, CircuitZone } from "@/data/circuit-data";

export const nurburgringZones: CircuitZone[] = [
  {
    "key": "nurburg",
    "name": "Nürburg",
    "driveMin": 0,
    "ring": 1,
    "count": 10
  },
  {
    "key": "meuspath",
    "name": "Meuspath",
    "driveMin": 3,
    "ring": 1,
    "count": 2
  },
  {
    "key": "mullenbach",
    "name": "Müllenbach",
    "driveMin": 3,
    "ring": 1,
    "count": 1
  },
  {
    "key": "drees",
    "name": "Drees",
    "driveMin": 5,
    "ring": 1,
    "count": 1
  },
  {
    "key": "wiesemscheid",
    "name": "Wiesemscheid",
    "driveMin": 5,
    "ring": 1,
    "count": 1
  },
  {
    "key": "adenau",
    "name": "Adenau",
    "driveMin": 6,
    "ring": 1,
    "count": 4
  },
  {
    "key": "barweiler",
    "name": "Barweiler",
    "driveMin": 7,
    "ring": 1,
    "count": 1
  },
  {
    "key": "honerath",
    "name": "Honerath",
    "driveMin": 7,
    "ring": 1,
    "count": 1
  },
  {
    "key": "boos",
    "name": "Boos",
    "driveMin": 7,
    "ring": 1,
    "count": 1
  }
];

export const nurburgringHotels: CircuitHotel[] = [
  {
    "name": "Dorint Am Nürburgring Hocheifel",
    "slug": "dorint-am-nurburgring-hocheifel",
    "kind": "hotel",
    "category": 3,
    "zone": "nurburg",
    "driveMin": 0,
    "ring": 1,
    "score": 4.6,
    "img": "/images/circuits/nurburgring/dorint-am-nurburgring-hocheifel.jpg"
  },
  {
    "name": "Pension N-Ring",
    "slug": "pension-n-ring",
    "kind": "rental",
    "category": 3,
    "zone": "nurburg",
    "driveMin": 0,
    "ring": 1,
    "score": 4.9,
    "img": "/images/circuits/nurburgring/pension-n-ring.jpg"
  },
  {
    "name": "Haus Pit Lane",
    "slug": "haus-pit-lane",
    "kind": "rental",
    "category": 3,
    "zone": "nurburg",
    "driveMin": 0,
    "ring": 1,
    "score": 4.8,
    "img": "/images/circuits/nurburgring/haus-pit-lane.jpg"
  },
  {
    "name": "Hotel am Tiergarten",
    "slug": "hotel-am-tiergarten",
    "kind": "hotel",
    "category": 3,
    "zone": "nurburg",
    "driveMin": 0,
    "ring": 1,
    "score": 4.7,
    "img": "/images/circuits/nurburgring/hotel-am-tiergarten.jpg"
  },
  {
    "name": "l-gut Race Hotel zur Burg Nürburg",
    "slug": "l-gut-race-hotel-zur-burg-nurburg",
    "kind": "hotel",
    "category": 3,
    "zone": "nurburg",
    "driveMin": 0,
    "ring": 1,
    "score": 4.5,
    "img": "/images/circuits/nurburgring/l-gut-race-hotel-zur-burg-nurburg.jpg"
  },
  {
    "name": "Nürburgring Congress Hotel",
    "slug": "nurburgring-congress-hotel",
    "kind": "hotel",
    "category": 3,
    "zone": "nurburg",
    "driveMin": 0,
    "ring": 1,
    "score": 4.5,
    "img": "/images/circuits/nurburgring/nurburgring-congress-hotel.jpg"
  },
  {
    "name": "Nürburgring Motorsport Hotel",
    "slug": "nurburgring-motorsport-hotel",
    "kind": "hotel",
    "category": 2,
    "zone": "nurburg",
    "driveMin": 0,
    "ring": 1,
    "score": 4.3,
    "img": "/images/circuits/nurburgring/nurburgring-motorsport-hotel.jpg"
  },
  {
    "name": "Motorsporthotel",
    "slug": "motorsporthotel",
    "kind": "hotel",
    "category": 2,
    "zone": "nurburg",
    "driveMin": 0,
    "ring": 1,
    "score": 4.3,
    "img": "/images/circuits/nurburgring/motorsporthotel.jpg"
  },
  {
    "name": "DF AM RING NÜRBURG HOTEL",
    "slug": "df-am-ring-nurburg-hotel",
    "kind": "hotel",
    "category": 1,
    "zone": "nurburg",
    "driveMin": 0,
    "ring": 1,
    "score": 3.5,
    "img": "/images/circuits/nurburgring/df-am-ring-nurburg-hotel.jpg"
  },
  {
    "name": "Ringhaus - Home of Silver Arrow",
    "slug": "ringhaus-home-of-silver-arrow",
    "kind": "rental",
    "category": 3,
    "zone": "nurburg",
    "driveMin": 3,
    "ring": 1,
    "score": 4.7,
    "img": "/images/circuits/nurburgring/ringhaus-home-of-silver-arrow.jpg"
  },
  {
    "name": "Hotel am Ring",
    "slug": "hotel-am-ring",
    "kind": "hotel",
    "category": 3,
    "zone": "meuspath",
    "driveMin": 3,
    "ring": 1,
    "score": 4.7,
    "img": "/images/circuits/nurburgring/hotel-am-ring.jpg"
  },
  {
    "name": "Campingplatz Meuspath am Nürburgring",
    "slug": "campingplatz-meuspath-am-nurburgring",
    "kind": "camping",
    "category": 2,
    "zone": "meuspath",
    "driveMin": 3,
    "ring": 1,
    "score": 4,
    "img": "/images/circuits/nurburgring/campingplatz-meuspath-am-nurburgring.jpg"
  },
  {
    "name": "Camping at the Nürburgring",
    "slug": "camping-at-the-nurburgring",
    "kind": "camping",
    "category": 1,
    "zone": "mullenbach",
    "driveMin": 3,
    "ring": 1,
    "score": 3.6,
    "img": "/images/circuits/nurburgring/camping-at-the-nurburgring.jpg"
  },
  {
    "name": "Nürburgring Ferienpark",
    "slug": "nurburgring-ferienpark",
    "kind": "hotel",
    "category": 3,
    "zone": "drees",
    "driveMin": 5,
    "ring": 1,
    "score": 4.7,
    "img": "/images/circuits/nurburgring/nurburgring-ferienpark.jpg"
  },
  {
    "name": "Hotel Rieder",
    "slug": "hotel-rieder",
    "kind": "hotel",
    "category": 3,
    "zone": "wiesemscheid",
    "driveMin": 5,
    "ring": 1,
    "score": 4.6,
    "img": "/images/circuits/nurburgring/hotel-rieder.jpg"
  },
  {
    "name": "Guesthouse Cockpit",
    "slug": "guesthouse-cockpit",
    "kind": "rental",
    "category": 3,
    "zone": "adenau",
    "driveMin": 6,
    "ring": 1,
    "score": 4.9,
    "img": "/images/circuits/nurburgring/guesthouse-cockpit.jpg"
  },
  {
    "name": "Hotel an der Nordschleife",
    "slug": "hotel-an-der-nordschleife",
    "kind": "hotel",
    "category": 3,
    "zone": "adenau",
    "driveMin": 6,
    "ring": 1,
    "score": 4.6,
    "img": "/images/circuits/nurburgring/hotel-an-der-nordschleife.jpg"
  },
  {
    "name": "Landhaus Sonnenhof",
    "slug": "landhaus-sonnenhof",
    "kind": "hotel",
    "category": 2,
    "zone": "adenau",
    "driveMin": 6,
    "ring": 1,
    "score": 4.3,
    "img": "/images/circuits/nurburgring/landhaus-sonnenhof.jpg"
  },
  {
    "name": "Nürburgring Rooms Pinocchio",
    "slug": "nurburgring-rooms-pinocchio",
    "kind": "hotel",
    "category": 2,
    "zone": "adenau",
    "driveMin": 6,
    "ring": 1,
    "score": 4.1,
    "img": "/images/circuits/nurburgring/nurburgring-rooms-pinocchio.jpg"
  },
  {
    "name": "Fast Lane Hotel",
    "slug": "fast-lane-hotel",
    "kind": "hotel",
    "category": 3,
    "zone": "barweiler",
    "driveMin": 7,
    "ring": 1,
    "score": 4.8,
    "img": "/images/circuits/nurburgring/fast-lane-hotel.jpg"
  },
  {
    "name": "GT3 Hotel",
    "slug": "gt3-hotel",
    "kind": "hotel",
    "category": 3,
    "zone": "honerath",
    "driveMin": 7,
    "ring": 1,
    "score": 4.8,
    "img": "/images/circuits/nurburgring/gt3-hotel.jpg"
  },
  {
    "name": "Eifelhotel Fuchs GmbH",
    "slug": "eifelhotel-fuchs-gmbh",
    "kind": "hotel",
    "category": 3,
    "zone": "boos",
    "driveMin": 7,
    "ring": 1,
    "score": 4.7,
    "img": "/images/circuits/nurburgring/eifelhotel-fuchs-gmbh.jpg"
  }
];
