// AUTO-GENERATED by scripts/gen-circuit-ts.mjs from an Apify scrape.
// Do not edit by hand — re-run the generator to refresh.
import type { CircuitHotel, CircuitZone } from "@/data/circuit-data";

export const silverstoneZones: CircuitZone[] = [
  {
    "key": "towcester",
    "name": "Towcester",
    "driveMin": 0,
    "ring": 1,
    "count": 17
  },
  {
    "key": "buckingham",
    "name": "Buckingham",
    "driveMin": 3,
    "ring": 1,
    "count": 6
  },
  {
    "key": "brackley",
    "name": "Brackley",
    "driveMin": 3,
    "ring": 1,
    "count": 3
  },
  {
    "key": "northampton",
    "name": "Northampton",
    "driveMin": 17,
    "ring": 2,
    "count": 2
  },
  {
    "key": "daventry",
    "name": "Daventry",
    "driveMin": 21,
    "ring": 2,
    "count": 1
  },
  {
    "key": "milton-keynes",
    "name": "Milton Keynes",
    "driveMin": 21,
    "ring": 2,
    "count": 1
  },
  {
    "key": "bicester",
    "name": "Bicester",
    "driveMin": 22,
    "ring": 2,
    "count": 1
  }
];

export const silverstoneHotels: CircuitHotel[] = [
  {
    "name": "Marshal Campsite",
    "slug": "marshal-campsite",
    "kind": "camping",
    "category": 2,
    "zone": "towcester",
    "driveMin": 0,
    "ring": 1,
    "score": 4.3,
    "img": "/images/circuits/silverstone/marshal-campsite.jpg"
  },
  {
    "name": "Homeside B & B",
    "slug": "homeside-b-b",
    "kind": "rental",
    "category": 3,
    "zone": "towcester",
    "driveMin": 0,
    "ring": 1,
    "score": 4.9,
    "img": "/images/circuits/silverstone/homeside-b-b.jpg"
  },
  {
    "name": "West End Paddocks Camping and Car Parking",
    "slug": "west-end-paddocks-camping-and-car-parking",
    "kind": "camping",
    "category": 3,
    "zone": "towcester",
    "driveMin": 0,
    "ring": 1,
    "score": 4.7,
    "img": "/images/circuits/silverstone/west-end-paddocks-camping-and-car-parking.jpg"
  },
  {
    "name": "Woodcote Fields - Official Silverstone Campsite",
    "slug": "woodcote-fields-official-silverstone-campsite",
    "kind": "camping",
    "category": 3,
    "zone": "towcester",
    "driveMin": 0,
    "ring": 1,
    "score": 4.6,
    "img": "/images/circuits/silverstone/woodcote-fields-official-silverstone-campsite.jpg"
  },
  {
    "name": "Silverstone B&B",
    "slug": "silverstone-b-b",
    "kind": "rental",
    "category": 2,
    "zone": "towcester",
    "driveMin": 0,
    "ring": 1,
    "score": 4.4,
    "img": "/images/circuits/silverstone/silverstone-b-b.jpg"
  },
  {
    "name": "Escapade Silverstone",
    "slug": "escapade-silverstone",
    "kind": "hotel",
    "category": 2,
    "zone": "towcester",
    "driveMin": 0,
    "ring": 1,
    "score": 4.4,
    "img": "/images/circuits/silverstone/escapade-silverstone.jpg"
  },
  {
    "name": "Hilton Garden Inn Silverstone",
    "slug": "hilton-garden-inn-silverstone",
    "kind": "hotel",
    "category": 2,
    "zone": "towcester",
    "driveMin": 0,
    "ring": 1,
    "score": 4.4,
    "img": "/images/circuits/silverstone/hilton-garden-inn-silverstone.jpg"
  },
  {
    "name": "Whittlebury Park",
    "slug": "whittlebury-park",
    "kind": "hotel",
    "category": 2,
    "zone": "towcester",
    "driveMin": 0,
    "ring": 1,
    "score": 4.2,
    "img": "/images/circuits/silverstone/whittlebury-park.jpg"
  },
  {
    "name": "BRDC Campsite",
    "slug": "brdc-campsite",
    "kind": "camping",
    "category": 1,
    "zone": "towcester",
    "driveMin": 0,
    "ring": 1,
    "score": 3.7,
    "img": "/images/circuits/silverstone/brdc-campsite.jpg"
  },
  {
    "name": "Pitstop Glamping - Silverstone",
    "slug": "pitstop-glamping-silverstone",
    "kind": "camping",
    "category": 3,
    "zone": "towcester",
    "driveMin": 3,
    "ring": 1,
    "score": 5,
    "img": "/images/circuits/silverstone/pitstop-glamping-silverstone.jpg"
  },
  {
    "name": "New Rookery Farm Campsite",
    "slug": "new-rookery-farm-campsite",
    "kind": "camping",
    "category": 3,
    "zone": "towcester",
    "driveMin": 3,
    "ring": 1,
    "score": 5,
    "img": "/images/circuits/silverstone/new-rookery-farm-campsite.jpg"
  },
  {
    "name": "Pavilion GP Camping",
    "slug": "pavilion-gp-camping",
    "kind": "camping",
    "category": 3,
    "zone": "towcester",
    "driveMin": 3,
    "ring": 1,
    "score": 5,
    "img": "/images/circuits/silverstone/pavilion-gp-camping.jpg"
  },
  {
    "name": "Silverstone Farm Campsite",
    "slug": "silverstone-farm-campsite",
    "kind": "camping",
    "category": 3,
    "zone": "towcester",
    "driveMin": 3,
    "ring": 1,
    "score": 4.8,
    "img": "/images/circuits/silverstone/silverstone-farm-campsite.jpg"
  },
  {
    "name": "Hamilton Fields Campsite, Silverstone",
    "slug": "hamilton-fields-campsite-silverstone",
    "kind": "camping",
    "category": 3,
    "zone": "towcester",
    "driveMin": 3,
    "ring": 1,
    "score": 4.6,
    "img": "/images/circuits/silverstone/hamilton-fields-campsite-silverstone.jpg"
  },
  {
    "name": "Windmill Farm Campsite",
    "slug": "windmill-farm-campsite",
    "kind": "camping",
    "category": 3,
    "zone": "towcester",
    "driveMin": 3,
    "ring": 1,
    "score": 4.6,
    "img": "/images/circuits/silverstone/windmill-farm-campsite.jpg"
  },
  {
    "name": "Silverstone Woodlands Campsite",
    "slug": "silverstone-woodlands-campsite",
    "kind": "camping",
    "category": 2,
    "zone": "buckingham",
    "driveMin": 3,
    "ring": 1,
    "score": 4.4,
    "img": "/images/circuits/silverstone/silverstone-woodlands-campsite.jpg"
  },
  {
    "name": "Dadford Road Campsite & Parking",
    "slug": "dadford-road-campsite-parking",
    "kind": "camping",
    "category": 2,
    "zone": "buckingham",
    "driveMin": 3,
    "ring": 1,
    "score": 4.4,
    "img": "/images/circuits/silverstone/dadford-road-campsite-parking.jpg"
  },
  {
    "name": "Silverstone Campsites ( At Silverstone Golf Club)",
    "slug": "silverstone-campsites-at-silverstone-golf-club",
    "kind": "camping",
    "category": 2,
    "zone": "buckingham",
    "driveMin": 3,
    "ring": 1,
    "score": 4.3,
    "img": "/images/circuits/silverstone/silverstone-campsites-at-silverstone-golf-club.jpg"
  },
  {
    "name": "Premier Inn Silverstone hotel",
    "slug": "premier-inn-silverstone-hotel",
    "kind": "hotel",
    "category": 2,
    "zone": "brackley",
    "driveMin": 3,
    "ring": 1,
    "score": 4,
    "img": "/images/circuits/silverstone/premier-inn-silverstone-hotel.jpg"
  },
  {
    "name": "Cartmel Fields Camping",
    "slug": "cartmel-fields-camping",
    "kind": "camping",
    "category": 2,
    "zone": "buckingham",
    "driveMin": 5,
    "ring": 1,
    "score": 4.4,
    "img": "/images/circuits/silverstone/cartmel-fields-camping.jpg"
  },
  {
    "name": "Travelodge Towcester Silverstone",
    "slug": "travelodge-towcester-silverstone",
    "kind": "hotel",
    "category": 2,
    "zone": "towcester",
    "driveMin": 6,
    "ring": 1,
    "score": 3.9,
    "img": "/images/circuits/silverstone/travelodge-towcester-silverstone.jpg"
  },
  {
    "name": "Saracens Head Hotel",
    "slug": "saracens-head-hotel",
    "kind": "hotel",
    "category": 3,
    "zone": "towcester",
    "driveMin": 7,
    "ring": 1,
    "score": 4.6,
    "img": "/images/circuits/silverstone/saracens-head-hotel.jpg"
  },
  {
    "name": "Astwell Mill Luxury B&B and Shepherds Hut",
    "slug": "astwell-mill-luxury-b-b-and-shepherds-hut",
    "kind": "rental",
    "category": 3,
    "zone": "brackley",
    "driveMin": 8,
    "ring": 1,
    "score": 4.7,
    "img": "/images/circuits/silverstone/astwell-mill-luxury-b-b-and-shepherds-hut.jpg"
  },
  {
    "name": "Villiers Hotel Buckingham",
    "slug": "villiers-hotel-buckingham",
    "kind": "hotel",
    "category": 2,
    "zone": "buckingham",
    "driveMin": 10,
    "ring": 1,
    "score": 4.2,
    "img": "/images/circuits/silverstone/villiers-hotel-buckingham.jpg"
  },
  {
    "name": "Premier Inn Buckingham hotel",
    "slug": "premier-inn-buckingham-hotel",
    "kind": "hotel",
    "category": 2,
    "zone": "buckingham",
    "driveMin": 12,
    "ring": 1,
    "score": 4.3,
    "img": "/images/circuits/silverstone/premier-inn-buckingham-hotel.jpg"
  },
  {
    "name": "Crown Hotel",
    "slug": "crown-hotel",
    "kind": "hotel",
    "category": 1,
    "zone": "brackley",
    "driveMin": 13,
    "ring": 1,
    "score": 2.9,
    "img": "/images/circuits/silverstone/crown-hotel.jpg"
  },
  {
    "name": "Holiday Inn Express Northampton - South by IHG",
    "slug": "holiday-inn-express-northampton-south-by-ihg",
    "kind": "hotel",
    "category": 2,
    "zone": "northampton",
    "driveMin": 17,
    "ring": 2,
    "score": 4.3,
    "img": "/images/circuits/silverstone/holiday-inn-express-northampton-south-by-ihg.jpg"
  },
  {
    "name": "Hilton Northampton",
    "slug": "hilton-northampton",
    "kind": "hotel",
    "category": 2,
    "zone": "northampton",
    "driveMin": 17,
    "ring": 2,
    "score": 4.1,
    "img": "/images/circuits/silverstone/hilton-northampton.jpg"
  },
  {
    "name": "Fawsley Hall Hotel & Spa",
    "slug": "fawsley-hall-hotel-spa",
    "kind": "hotel",
    "category": 3,
    "zone": "daventry",
    "driveMin": 21,
    "ring": 2,
    "score": 4.6,
    "img": "/images/circuits/silverstone/fawsley-hall-hotel-spa.jpg"
  },
  {
    "name": "Horwood House Hotel",
    "slug": "horwood-house-hotel",
    "kind": "hotel",
    "category": 2,
    "zone": "milton-keynes",
    "driveMin": 21,
    "ring": 2,
    "score": 4,
    "img": "/images/circuits/silverstone/horwood-house-hotel.jpg"
  },
  {
    "name": "Travelodge Bicester Cherwell Valley M40",
    "slug": "travelodge-bicester-cherwell-valley-m40",
    "kind": "hotel",
    "category": 2,
    "zone": "bicester",
    "driveMin": 22,
    "ring": 2,
    "score": 3.9,
    "img": "/images/circuits/silverstone/travelodge-bicester-cherwell-valley-m40.jpg"
  }
];
