// AUTO-GENERATED by scripts/gen-circuit-ts.mjs from an Apify scrape.
// Do not edit by hand — re-run the generator to refresh.
import type { CircuitHotel, CircuitZone } from "@/data/circuit-data";

export const spaZones: CircuitZone[] = [
  {
    "key": "stavelot",
    "name": "Stavelot",
    "driveMin": 0,
    "ring": 1,
    "count": 21
  },
  {
    "key": "malmedy",
    "name": "Malmedy",
    "driveMin": 3,
    "ring": 1,
    "count": 8
  },
  {
    "key": "ruy",
    "name": "Ruy",
    "driveMin": 6,
    "ring": 1,
    "count": 1
  },
  {
    "key": "sart",
    "name": "Sart",
    "driveMin": 10,
    "ring": 1,
    "count": 1
  },
  {
    "key": "jalhay",
    "name": "Jalhay",
    "driveMin": 12,
    "ring": 1,
    "count": 1
  },
  {
    "key": "spa",
    "name": "Spa",
    "driveMin": 12,
    "ring": 1,
    "count": 2
  },
  {
    "key": "waimes",
    "name": "Waimes",
    "driveMin": 13,
    "ring": 1,
    "count": 1
  },
  {
    "key": "theux",
    "name": "Theux",
    "driveMin": 15,
    "ring": 1,
    "count": 1
  }
];

export const spaHotels: CircuitHotel[] = [
  {
    "name": "GPtents",
    "slug": "gptents",
    "kind": "camping",
    "category": 3,
    "zone": "stavelot",
    "driveMin": 0,
    "ring": 1,
    "score": 4.9,
    "img": "/images/circuits/spa/gptents.jpg"
  },
  {
    "name": "Hotel De La Source",
    "slug": "hotel-de-la-source",
    "kind": "hotel",
    "category": 2,
    "zone": "stavelot",
    "driveMin": 0,
    "ring": 1,
    "score": 4.4,
    "img": "/images/circuits/spa/hotel-de-la-source.jpg"
  },
  {
    "name": "Yellow Camping Spa",
    "slug": "yellow-camping-spa",
    "kind": "camping",
    "category": 2,
    "zone": "stavelot",
    "driveMin": 0,
    "ring": 1,
    "score": 3.8,
    "img": "/images/circuits/spa/yellow-camping-spa.jpg"
  },
  {
    "name": "La tanière du bois du loup",
    "slug": "la-taniere-du-bois-du-loup",
    "kind": "rental",
    "category": 3,
    "zone": "malmedy",
    "driveMin": 3,
    "ring": 1,
    "score": 5,
    "img": "/images/circuits/spa/la-taniere-du-bois-du-loup.jpg"
  },
  {
    "name": "Appartement de l'Open Source",
    "slug": "appartement-de-l-open-source",
    "kind": "rental",
    "category": 3,
    "zone": "stavelot",
    "driveMin": 3,
    "ring": 1,
    "score": 4.7,
    "img": "/images/circuits/spa/appartement-de-l-open-source.jpg"
  },
  {
    "name": "Camping 37",
    "slug": "camping-37",
    "kind": "camping",
    "category": 3,
    "zone": "stavelot",
    "driveMin": 3,
    "ring": 1,
    "score": 4.6,
    "img": "/images/circuits/spa/camping-37.jpg"
  },
  {
    "name": "Camping Les Ecuries F1",
    "slug": "camping-les-ecuries-f1",
    "kind": "camping",
    "category": 3,
    "zone": "malmedy",
    "driveMin": 3,
    "ring": 1,
    "score": 4.5,
    "img": "/images/circuits/spa/camping-les-ecuries-f1.jpg"
  },
  {
    "name": "Camping",
    "slug": "camping",
    "kind": "camping",
    "category": 3,
    "zone": "malmedy",
    "driveMin": 3,
    "ring": 1,
    "score": 4.5,
    "img": "/images/circuits/spa/camping.jpg"
  },
  {
    "name": "Dolce Villa",
    "slug": "dolce-villa",
    "kind": "hotel",
    "category": 3,
    "zone": "stavelot",
    "driveMin": 3,
    "ring": 1,
    "score": 4.5,
    "img": "/images/circuits/spa/dolce-villa.jpg"
  },
  {
    "name": "The Elephant F1 Camping",
    "slug": "the-elephant-f1-camping",
    "kind": "camping",
    "category": 2,
    "zone": "stavelot",
    "driveMin": 3,
    "ring": 1,
    "score": 4.4,
    "img": "/images/circuits/spa/the-elephant-f1-camping.jpg"
  },
  {
    "name": "Camping35",
    "slug": "camping35",
    "kind": "camping",
    "category": 2,
    "zone": "stavelot",
    "driveMin": 3,
    "ring": 1,
    "score": 4.4,
    "img": "/images/circuits/spa/camping35.jpg"
  },
  {
    "name": "Le Roannay - Hôtel & Restaurant gastronomique",
    "slug": "le-roannay-hotel-restaurant-gastronomique",
    "kind": "hotel",
    "category": 2,
    "zone": "stavelot",
    "driveMin": 3,
    "ring": 1,
    "score": 4.4,
    "img": "/images/circuits/spa/le-roannay-hotel-restaurant-gastronomique.jpg"
  },
  {
    "name": "Hotel - Relais de Pommard | Francorchamps",
    "slug": "hotel-relais-de-pommard-francorchamps",
    "kind": "hotel",
    "category": 2,
    "zone": "stavelot",
    "driveMin": 3,
    "ring": 1,
    "score": 4.4,
    "img": "/images/circuits/spa/hotel-relais-de-pommard-francorchamps.jpg"
  },
  {
    "name": "Full Wind Francorchamps",
    "slug": "full-wind-francorchamps",
    "kind": "hotel",
    "category": 1,
    "zone": "malmedy",
    "driveMin": 3,
    "ring": 1,
    "score": 3.7,
    "img": "/images/circuits/spa/full-wind-francorchamps.jpg"
  },
  {
    "name": "Spa Family Camping - Circuit Spa-Francorchamps",
    "slug": "spa-family-camping-circuit-spa-francorchamps",
    "kind": "camping",
    "category": 3,
    "zone": "stavelot",
    "driveMin": 3,
    "ring": 1,
    "score": 5,
    "img": "/images/circuits/spa/spa-family-camping-circuit-spa-francorchamps.jpg"
  },
  {
    "name": "The View",
    "slug": "the-view",
    "kind": "rental",
    "category": 3,
    "zone": "stavelot",
    "driveMin": 3,
    "ring": 1,
    "score": 4.9,
    "img": "/images/circuits/spa/the-view.jpg"
  },
  {
    "name": "La Colombe",
    "slug": "la-colombe",
    "kind": "rental",
    "category": 3,
    "zone": "stavelot",
    "driveMin": 3,
    "ring": 1,
    "score": 4.9,
    "img": "/images/circuits/spa/la-colombe.jpg"
  },
  {
    "name": "Camping de L'Eau Rouge",
    "slug": "camping-de-l-eau-rouge",
    "kind": "camping",
    "category": 2,
    "zone": "stavelot",
    "driveMin": 3,
    "ring": 1,
    "score": 4.3,
    "img": "/images/circuits/spa/camping-de-l-eau-rouge.jpg"
  },
  {
    "name": "Spa Family Camping - F1 Yellow area 68",
    "slug": "spa-family-camping-f1-yellow-area-68",
    "kind": "camping",
    "category": 2,
    "zone": "stavelot",
    "driveMin": 3,
    "ring": 1,
    "score": 4,
    "img": "/images/circuits/spa/spa-family-camping-f1-yellow-area-68.jpg"
  },
  {
    "name": "Yellow camping Francorchamps",
    "slug": "yellow-camping-francorchamps",
    "kind": "camping",
    "category": 1,
    "zone": "stavelot",
    "driveMin": 3,
    "ring": 1,
    "score": 3.4,
    "img": "/images/circuits/spa/yellow-camping-francorchamps.jpg"
  },
  {
    "name": "IntentsGP Campsite",
    "slug": "intentsgp-campsite",
    "kind": "camping",
    "category": 1,
    "zone": "stavelot",
    "driveMin": 3,
    "ring": 1,
    "score": 2.9,
    "img": "/images/circuits/spa/intentsgp-campsite.jpg"
  },
  {
    "name": "Camping Yellow 75",
    "slug": "camping-yellow-75",
    "kind": "camping",
    "category": 1,
    "zone": "stavelot",
    "driveMin": 3,
    "ring": 1,
    "score": 2,
    "img": "/images/circuits/spa/camping-yellow-75.jpg"
  },
  {
    "name": "Myhotel",
    "slug": "myhotel",
    "kind": "hotel",
    "category": 3,
    "zone": "malmedy",
    "driveMin": 5,
    "ring": 1,
    "score": 4.6,
    "img": "/images/circuits/spa/myhotel.jpg"
  },
  {
    "name": "Hôtel La Forge SA",
    "slug": "hotel-la-forge-sa",
    "kind": "hotel",
    "category": 1,
    "zone": "malmedy",
    "driveMin": 5,
    "ring": 1,
    "score": 2.5,
    "img": "/images/circuits/spa/hotel-la-forge-sa.jpg"
  },
  {
    "name": "Le paddock lodge",
    "slug": "le-paddock-lodge",
    "kind": "rental",
    "category": 3,
    "zone": "ruy",
    "driveMin": 6,
    "ring": 1,
    "score": 4.9,
    "img": "/images/circuits/spa/le-paddock-lodge.jpg"
  },
  {
    "name": "Le Val d'Amblève",
    "slug": "le-val-d-ambleve",
    "kind": "hotel",
    "category": 3,
    "zone": "stavelot",
    "driveMin": 6,
    "ring": 1,
    "score": 4.7,
    "img": "/images/circuits/spa/le-val-d-ambleve.jpg"
  },
  {
    "name": "Hotel Grand Champ",
    "slug": "hotel-grand-champ",
    "kind": "hotel",
    "category": 2,
    "zone": "malmedy",
    "driveMin": 6,
    "ring": 1,
    "score": 4.3,
    "img": "/images/circuits/spa/hotel-grand-champ.jpg"
  },
  {
    "name": "Camping De Challes",
    "slug": "camping-de-challes",
    "kind": "camping",
    "category": 1,
    "zone": "stavelot",
    "driveMin": 6,
    "ring": 1,
    "score": 3.6,
    "img": "/images/circuits/spa/camping-de-challes.jpg"
  },
  {
    "name": "Arimont Valley Hotel",
    "slug": "arimont-valley-hotel",
    "kind": "hotel",
    "category": 2,
    "zone": "malmedy",
    "driveMin": 8,
    "ring": 1,
    "score": 4.3,
    "img": "/images/circuits/spa/arimont-valley-hotel.jpg"
  },
  {
    "name": "Camping de la Cascade",
    "slug": "camping-de-la-cascade",
    "kind": "camping",
    "category": 3,
    "zone": "stavelot",
    "driveMin": 9,
    "ring": 1,
    "score": 4.5,
    "img": "/images/circuits/spa/camping-de-la-cascade.jpg"
  },
  {
    "name": "Spa D 'Or",
    "slug": "spa-d-or",
    "kind": "camping",
    "category": 1,
    "zone": "sart",
    "driveMin": 10,
    "ring": 1,
    "score": 3.7,
    "img": "/images/circuits/spa/spa-d-or.jpg"
  },
  {
    "name": "les Refuges du Chalet",
    "slug": "les-refuges-du-chalet",
    "kind": "hotel",
    "category": 3,
    "zone": "jalhay",
    "driveMin": 12,
    "ring": 1,
    "score": 4.8,
    "img": "/images/circuits/spa/les-refuges-du-chalet.jpg"
  },
  {
    "name": "Van der Valk Hotel Spa",
    "slug": "van-der-valk-hotel-spa",
    "kind": "hotel",
    "category": 2,
    "zone": "spa",
    "driveMin": 12,
    "ring": 1,
    "score": 4.2,
    "img": "/images/circuits/spa/van-der-valk-hotel-spa.jpg"
  },
  {
    "name": "Radisson Blu Balmoral Hotel, Spa",
    "slug": "radisson-blu-balmoral-hotel-spa",
    "kind": "hotel",
    "category": 2,
    "zone": "spa",
    "driveMin": 12,
    "ring": 1,
    "score": 4,
    "img": "/images/circuits/spa/radisson-blu-balmoral-hotel-spa.jpg"
  },
  {
    "name": "Le Domaine Des Hautes Fagnes & Spa",
    "slug": "le-domaine-des-hautes-fagnes-spa",
    "kind": "hotel",
    "category": 1,
    "zone": "waimes",
    "driveMin": 13,
    "ring": 1,
    "score": 3.7,
    "img": "/images/circuits/spa/le-domaine-des-hautes-fagnes-spa.jpg"
  },
  {
    "name": "Camping Polleur in the Ardennes",
    "slug": "camping-polleur-in-the-ardennes",
    "kind": "camping",
    "category": 2,
    "zone": "theux",
    "driveMin": 15,
    "ring": 1,
    "score": 3.9,
    "img": "/images/circuits/spa/camping-polleur-in-the-ardennes.jpg"
  }
];
