// AUTO-GENERATED by scripts/gen-circuit-ts.mjs from an Apify scrape.
// Do not edit by hand — re-run the generator to refresh.
import type { CircuitHotel, CircuitZone } from "@/data/circuit-data";

export const spielbergZones: CircuitZone[] = [
  {
    "key": "spielberg",
    "name": "Spielberg",
    "driveMin": 0,
    "ring": 1,
    "count": 24
  },
  {
    "key": "circuit-area",
    "name": "Circuit area",
    "driveMin": 0,
    "ring": 1,
    "count": 1
  },
  {
    "key": "flatschach",
    "name": "Flatschach",
    "driveMin": 0,
    "ring": 1,
    "count": 1
  },
  {
    "key": "zeltweg",
    "name": "Zeltweg",
    "driveMin": 3,
    "ring": 1,
    "count": 5
  },
  {
    "key": "knittelfeld",
    "name": "Knittelfeld",
    "driveMin": 5,
    "ring": 1,
    "count": 4
  },
  {
    "key": "gro-lobming",
    "name": "Großlobming",
    "driveMin": 5,
    "ring": 1,
    "count": 1
  },
  {
    "key": "fohnsdorf",
    "name": "Fohnsdorf",
    "driveMin": 5,
    "ring": 1,
    "count": 5
  },
  {
    "key": "kleinlobming",
    "name": "Kleinlobming",
    "driveMin": 12,
    "ring": 1,
    "count": 1
  }
];

export const spielbergHotels: CircuitHotel[] = [
  {
    "name": "Camping VIOLETT Red Bull Ring",
    "slug": "camping-violett-red-bull-ring",
    "kind": "camping",
    "category": 3,
    "zone": "spielberg",
    "driveMin": 0,
    "ring": 1,
    "score": 4.9,
    "img": "/images/circuits/spielberg/camping-violett-red-bull-ring.jpg"
  },
  {
    "name": "Camping GRÜN - Moitzi Spielberg am Red Bull Ring",
    "slug": "camping-grun-moitzi-spielberg-am-red-bull-ring",
    "kind": "camping",
    "category": 3,
    "zone": "spielberg",
    "driveMin": 0,
    "ring": 1,
    "score": 4.6,
    "img": "/images/circuits/spielberg/camping-grun-moitzi-spielberg-am-red-bull-ring.jpg"
  },
  {
    "name": "Camping at the Red Bull Ring",
    "slug": "camping-at-the-red-bull-ring",
    "kind": "camping",
    "category": 2,
    "zone": "spielberg",
    "driveMin": 0,
    "ring": 1,
    "score": 4.3,
    "img": "/images/circuits/spielberg/camping-at-the-red-bull-ring.jpg"
  },
  {
    "name": "Spielberg CAMPING GELB beim Red Bull Ring",
    "slug": "spielberg-camping-gelb-beim-red-bull-ring",
    "kind": "camping",
    "category": 2,
    "zone": "spielberg",
    "driveMin": 0,
    "ring": 1,
    "score": 4.3,
    "img": "/images/circuits/spielberg/spielberg-camping-gelb-beim-red-bull-ring.jpg"
  },
  {
    "name": "GrandPrix.camp",
    "slug": "grandprix-camp",
    "kind": "camping",
    "category": 1,
    "zone": "spielberg",
    "driveMin": 0,
    "ring": 1,
    "score": 3.6,
    "img": "/images/circuits/spielberg/grandprix-camp.jpg"
  },
  {
    "name": "Formel 1 Lodge Camping Spielberg am Red Bull Ring",
    "slug": "formel-1-lodge-camping-spielberg-am-red-bull-ring",
    "kind": "hotel",
    "category": 3,
    "zone": "circuit-area",
    "driveMin": 0,
    "ring": 1,
    "score": 5,
    "img": "/images/circuits/spielberg/formel-1-lodge-camping-spielberg-am-red-bull-ring.jpg"
  },
  {
    "name": "Campingplatz Stürzl",
    "slug": "campingplatz-sturzl",
    "kind": "camping",
    "category": 3,
    "zone": "spielberg",
    "driveMin": 0,
    "ring": 1,
    "score": 5,
    "img": "/images/circuits/spielberg/campingplatz-sturzl.jpg"
  },
  {
    "name": "Haus Dietrich",
    "slug": "haus-dietrich",
    "kind": "hotel",
    "category": 3,
    "zone": "spielberg",
    "driveMin": 0,
    "ring": 1,
    "score": 4.7,
    "img": "/images/circuits/spielberg/haus-dietrich.jpg"
  },
  {
    "name": "Schönberghof Spielberg",
    "slug": "schonberghof-spielberg",
    "kind": "hotel",
    "category": 3,
    "zone": "spielberg",
    "driveMin": 0,
    "ring": 1,
    "score": 4.7,
    "img": "/images/circuits/spielberg/schonberghof-spielberg.jpg"
  },
  {
    "name": "Guesthouse Camping Edlinger Flatschach",
    "slug": "guesthouse-camping-edlinger-flatschach",
    "kind": "camping",
    "category": 3,
    "zone": "spielberg",
    "driveMin": 0,
    "ring": 1,
    "score": 4.6,
    "img": "/images/circuits/spielberg/guesthouse-camping-edlinger-flatschach.jpg"
  },
  {
    "name": "F&F Camping Blau Freitag-Filipovic",
    "slug": "f-f-camping-blau-freitag-filipovic",
    "kind": "camping",
    "category": 3,
    "zone": "spielberg",
    "driveMin": 0,
    "ring": 1,
    "score": 4.6,
    "img": "/images/circuits/spielberg/f-f-camping-blau-freitag-filipovic.jpg"
  },
  {
    "name": "GPtents | Camping F1 & MotoGP Spielberg, Austria",
    "slug": "gptents-camping-f1-motogp-spielberg-austria",
    "kind": "camping",
    "category": 3,
    "zone": "spielberg",
    "driveMin": 0,
    "ring": 1,
    "score": 4.6,
    "img": "/images/circuits/spielberg/gptents-camping-f1-motogp-spielberg-austria.jpg"
  },
  {
    "name": "Camping Pichler (BEIGE)",
    "slug": "camping-pichler-beige",
    "kind": "camping",
    "category": 3,
    "zone": "spielberg",
    "driveMin": 0,
    "ring": 1,
    "score": 4.5,
    "img": "/images/circuits/spielberg/camping-pichler-beige.jpg"
  },
  {
    "name": "Schitterhof CAMPING WEISS",
    "slug": "schitterhof-camping-weiss",
    "kind": "camping",
    "category": 3,
    "zone": "spielberg",
    "driveMin": 0,
    "ring": 1,
    "score": 4.5,
    "img": "/images/circuits/spielberg/schitterhof-camping-weiss.jpg"
  },
  {
    "name": "Camping Pink am Birkmoarhof",
    "slug": "camping-pink-am-birkmoarhof",
    "kind": "camping",
    "category": 2,
    "zone": "spielberg",
    "driveMin": 0,
    "ring": 1,
    "score": 4.4,
    "img": "/images/circuits/spielberg/camping-pink-am-birkmoarhof.jpg"
  },
  {
    "name": "Privatzimmer am Red Bull Ring",
    "slug": "privatzimmer-am-red-bull-ring",
    "kind": "hotel",
    "category": 2,
    "zone": "spielberg",
    "driveMin": 0,
    "ring": 1,
    "score": 4.2,
    "img": "/images/circuits/spielberg/privatzimmer-am-red-bull-ring.jpg"
  },
  {
    "name": "Camping Josef Schindelbacher",
    "slug": "camping-josef-schindelbacher",
    "kind": "camping",
    "category": 2,
    "zone": "flatschach",
    "driveMin": 0,
    "ring": 1,
    "score": 4.1,
    "img": "/images/circuits/spielberg/camping-josef-schindelbacher.jpg"
  },
  {
    "name": "Gästehaus Sigrid",
    "slug": "gastehaus-sigrid",
    "kind": "rental",
    "category": 3,
    "zone": "spielberg",
    "driveMin": 3,
    "ring": 1,
    "score": 4.9,
    "img": "/images/circuits/spielberg/gastehaus-sigrid.jpg"
  },
  {
    "name": "Camping Blau WESTSCHLEIFE - Schindelbacher Karin u. Hans",
    "slug": "camping-blau-westschleife-schindelbacher-karin-u-hans",
    "kind": "camping",
    "category": 3,
    "zone": "spielberg",
    "driveMin": 3,
    "ring": 1,
    "score": 4.9,
    "img": "/images/circuits/spielberg/camping-blau-westschleife-schindelbacher-karin-u-hans.jpg"
  },
  {
    "name": "Camping Kaltenbrunner",
    "slug": "camping-kaltenbrunner",
    "kind": "camping",
    "category": 3,
    "zone": "spielberg",
    "driveMin": 3,
    "ring": 1,
    "score": 4.8,
    "img": "/images/circuits/spielberg/camping-kaltenbrunner.jpg"
  },
  {
    "name": "Hotel Urfa",
    "slug": "hotel-urfa",
    "kind": "hotel",
    "category": 3,
    "zone": "zeltweg",
    "driveMin": 3,
    "ring": 1,
    "score": 4.8,
    "img": "/images/circuits/spielberg/hotel-urfa.jpg"
  },
  {
    "name": "Ring Rast Camping | near Red Bull Ring | F1 & MotoGP & Air Show Spielberg, Austria",
    "slug": "ring-rast-camping-near-red-bull-ring-f1-motogp-air-show-spielberg-austria",
    "kind": "camping",
    "category": 3,
    "zone": "spielberg",
    "driveMin": 3,
    "ring": 1,
    "score": 4.6,
    "img": "/images/circuits/spielberg/ring-rast-camping-near-red-bull-ring-f1-motogp-air-show-spielberg-austria.jpg"
  },
  {
    "name": "Burg Rooms",
    "slug": "burg-rooms",
    "kind": "hotel",
    "category": 2,
    "zone": "spielberg",
    "driveMin": 3,
    "ring": 1,
    "score": 4.4,
    "img": "/images/circuits/spielberg/burg-rooms.jpg"
  },
  {
    "name": "Camping Gruber",
    "slug": "camping-gruber",
    "kind": "camping",
    "category": 2,
    "zone": "spielberg",
    "driveMin": 3,
    "ring": 1,
    "score": 4.3,
    "img": "/images/circuits/spielberg/camping-gruber.jpg"
  },
  {
    "name": "Camping & Parking Spielberg | F1 & MotoGP | Easy Camping",
    "slug": "camping-parking-spielberg-f1-motogp-easy-camping",
    "kind": "camping",
    "category": 2,
    "zone": "spielberg",
    "driveMin": 3,
    "ring": 1,
    "score": 4.1,
    "img": "/images/circuits/spielberg/camping-parking-spielberg-f1-motogp-easy-camping.jpg"
  },
  {
    "name": "Steirerschlössl",
    "slug": "steirerschlossl",
    "kind": "hotel",
    "category": 3,
    "zone": "zeltweg",
    "driveMin": 3,
    "ring": 1,
    "score": 4.9,
    "img": "/images/circuits/spielberg/steirerschlossl.jpg"
  },
  {
    "name": "Die Schlafstube",
    "slug": "die-schlafstube",
    "kind": "rental",
    "category": 3,
    "zone": "zeltweg",
    "driveMin": 3,
    "ring": 1,
    "score": 4.9,
    "img": "/images/circuits/spielberg/die-schlafstube.jpg"
  },
  {
    "name": "ART HOTEL SPIELBERG",
    "slug": "art-hotel-spielberg",
    "kind": "hotel",
    "category": 2,
    "zone": "spielberg",
    "driveMin": 3,
    "ring": 1,
    "score": 4.4,
    "img": "/images/circuits/spielberg/art-hotel-spielberg.jpg"
  },
  {
    "name": "flexy.motel Spielberg",
    "slug": "flexy-motel-spielberg",
    "kind": "hotel",
    "category": 2,
    "zone": "spielberg",
    "driveMin": 3,
    "ring": 1,
    "score": 4.1,
    "img": "/images/circuits/spielberg/flexy-motel-spielberg.jpg"
  },
  {
    "name": "Angelika Esser private rooms",
    "slug": "angelika-esser-private-rooms",
    "kind": "rental",
    "category": 3,
    "zone": "knittelfeld",
    "driveMin": 5,
    "ring": 1,
    "score": 4.9,
    "img": "/images/circuits/spielberg/angelika-esser-private-rooms.jpg"
  },
  {
    "name": "G'Schlössl Murtal",
    "slug": "g-schlossl-murtal",
    "kind": "hotel",
    "category": 3,
    "zone": "gro-lobming",
    "driveMin": 5,
    "ring": 1,
    "score": 4.8,
    "img": "/images/circuits/spielberg/g-schlossl-murtal.jpg"
  },
  {
    "name": "Camping Wildbolz",
    "slug": "camping-wildbolz",
    "kind": "camping",
    "category": 3,
    "zone": "fohnsdorf",
    "driveMin": 5,
    "ring": 1,
    "score": 4.7,
    "img": "/images/circuits/spielberg/camping-wildbolz.jpg"
  },
  {
    "name": "MT Hotel",
    "slug": "mt-hotel",
    "kind": "hotel",
    "category": 3,
    "zone": "zeltweg",
    "driveMin": 5,
    "ring": 1,
    "score": 4.7,
    "img": "/images/circuits/spielberg/mt-hotel.jpg"
  },
  {
    "name": "Gewerkenschlössl Zeilinger",
    "slug": "gewerkenschlossl-zeilinger",
    "kind": "hotel",
    "category": 3,
    "zone": "knittelfeld",
    "driveMin": 5,
    "ring": 1,
    "score": 4.7,
    "img": "/images/circuits/spielberg/gewerkenschlossl-zeilinger.jpg"
  },
  {
    "name": "Motel Zeltweg - Self Check-in",
    "slug": "motel-zeltweg-self-check-in",
    "kind": "hotel",
    "category": 3,
    "zone": "zeltweg",
    "driveMin": 5,
    "ring": 1,
    "score": 4.6,
    "img": "/images/circuits/spielberg/motel-zeltweg-self-check-in.jpg"
  },
  {
    "name": "Das Friedrich",
    "slug": "das-friedrich",
    "kind": "hotel",
    "category": 3,
    "zone": "knittelfeld",
    "driveMin": 6,
    "ring": 1,
    "score": 4.7,
    "img": "/images/circuits/spielberg/das-friedrich.jpg"
  },
  {
    "name": "Landhaus Wilhelmer",
    "slug": "landhaus-wilhelmer",
    "kind": "hotel",
    "category": 3,
    "zone": "fohnsdorf",
    "driveMin": 6,
    "ring": 1,
    "score": 4.7,
    "img": "/images/circuits/spielberg/landhaus-wilhelmer.jpg"
  },
  {
    "name": "Pauls Hotel",
    "slug": "pauls-hotel",
    "kind": "hotel",
    "category": 2,
    "zone": "knittelfeld",
    "driveMin": 6,
    "ring": 1,
    "score": 4.2,
    "img": "/images/circuits/spielberg/pauls-hotel.jpg"
  },
  {
    "name": "Hotel Fohnsdorf",
    "slug": "hotel-fohnsdorf",
    "kind": "hotel",
    "category": 2,
    "zone": "fohnsdorf",
    "driveMin": 8,
    "ring": 1,
    "score": 4.4,
    "img": "/images/circuits/spielberg/hotel-fohnsdorf.jpg"
  },
  {
    "name": "Schloss Gabelhofen",
    "slug": "schloss-gabelhofen",
    "kind": "hotel",
    "category": 3,
    "zone": "fohnsdorf",
    "driveMin": 9,
    "ring": 1,
    "score": 4.8,
    "img": "/images/circuits/spielberg/schloss-gabelhofen.jpg"
  },
  {
    "name": "Das Karl August",
    "slug": "das-karl-august",
    "kind": "hotel",
    "category": 3,
    "zone": "fohnsdorf",
    "driveMin": 9,
    "ring": 1,
    "score": 4.8,
    "img": "/images/circuits/spielberg/das-karl-august.jpg"
  },
  {
    "name": "Gasthof & Pension Hubmann",
    "slug": "gasthof-pension-hubmann",
    "kind": "rental",
    "category": 3,
    "zone": "kleinlobming",
    "driveMin": 12,
    "ring": 1,
    "score": 4.8,
    "img": "/images/circuits/spielberg/gasthof-pension-hubmann.jpg"
  }
];
