// AUTO-GENERATED by scripts/gen-circuit-ts.mjs from an Apify scrape.
// Do not edit by hand — re-run the generator to refresh.
import type { CircuitHotel, CircuitZone } from "@/data/circuit-data";

export const zandvoortZones: CircuitZone[] = [
  {
    "key": "zandvoort",
    "name": "Zandvoort",
    "driveMin": 0,
    "ring": 1,
    "count": 24
  },
  {
    "key": "overveen",
    "name": "Overveen",
    "driveMin": 3,
    "ring": 1,
    "count": 1
  },
  {
    "key": "santpoort-zuid",
    "name": "Santpoort-Zuid",
    "driveMin": 8,
    "ring": 1,
    "count": 1
  }
];

export const zandvoortHotels: CircuitHotel[] = [
  {
    "name": "Camping Association Amsterdam",
    "slug": "camping-association-amsterdam",
    "kind": "camping",
    "category": 3,
    "zone": "zandvoort",
    "driveMin": 0,
    "ring": 1,
    "score": 4.7,
    "img": "/images/circuits/zandvoort/camping-association-amsterdam.jpg"
  },
  {
    "name": "Hotel Beachhouse",
    "slug": "hotel-beachhouse",
    "kind": "hotel",
    "category": 3,
    "zone": "zandvoort",
    "driveMin": 0,
    "ring": 1,
    "score": 4.5,
    "img": "/images/circuits/zandvoort/hotel-beachhouse.jpg"
  },
  {
    "name": "Camping De Duinrand",
    "slug": "camping-de-duinrand",
    "kind": "camping",
    "category": 2,
    "zone": "zandvoort",
    "driveMin": 0,
    "ring": 1,
    "score": 4.2,
    "img": "/images/circuits/zandvoort/camping-de-duinrand.jpg"
  },
  {
    "name": "Camperplaats Zandvoort",
    "slug": "camperplaats-zandvoort",
    "kind": "camping",
    "category": 1,
    "zone": "zandvoort",
    "driveMin": 0,
    "ring": 1,
    "score": 3.2,
    "img": "/images/circuits/zandvoort/camperplaats-zandvoort.jpg"
  },
  {
    "name": "Center Parcs Strandhotel",
    "slug": "center-parcs-strandhotel",
    "kind": "hotel",
    "category": 2,
    "zone": "zandvoort",
    "driveMin": 0,
    "ring": 1,
    "score": 4,
    "img": "/images/circuits/zandvoort/center-parcs-strandhotel.jpg"
  },
  {
    "name": "Hotel NH Zandvoort",
    "slug": "hotel-nh-zandvoort",
    "kind": "hotel",
    "category": 2,
    "zone": "zandvoort",
    "driveMin": 0,
    "ring": 1,
    "score": 4,
    "img": "/images/circuits/zandvoort/hotel-nh-zandvoort.jpg"
  },
  {
    "name": "Blendin Hotel Bloemendaal",
    "slug": "blendin-hotel-bloemendaal",
    "kind": "hotel",
    "category": 3,
    "zone": "overveen",
    "driveMin": 3,
    "ring": 1,
    "score": 4.8,
    "img": "/images/circuits/zandvoort/blendin-hotel-bloemendaal.jpg"
  },
  {
    "name": "Bell-Hotel",
    "slug": "bell-hotel",
    "kind": "hotel",
    "category": 3,
    "zone": "zandvoort",
    "driveMin": 3,
    "ring": 1,
    "score": 4.7,
    "img": "/images/circuits/zandvoort/bell-hotel.jpg"
  },
  {
    "name": "Pension Zandvoort aan Zee",
    "slug": "pension-zandvoort-aan-zee",
    "kind": "rental",
    "category": 3,
    "zone": "zandvoort",
    "driveMin": 3,
    "ring": 1,
    "score": 4.6,
    "img": "/images/circuits/zandvoort/pension-zandvoort-aan-zee.jpg"
  },
  {
    "name": "Boutique Lodge Zandvoort",
    "slug": "boutique-lodge-zandvoort",
    "kind": "hotel",
    "category": 3,
    "zone": "zandvoort",
    "driveMin": 3,
    "ring": 1,
    "score": 4.6,
    "img": "/images/circuits/zandvoort/boutique-lodge-zandvoort.jpg"
  },
  {
    "name": "Aquarius Pension",
    "slug": "aquarius-pension",
    "kind": "rental",
    "category": 3,
    "zone": "zandvoort",
    "driveMin": 3,
    "ring": 1,
    "score": 4.5,
    "img": "/images/circuits/zandvoort/aquarius-pension.jpg"
  },
  {
    "name": "Guesthouse Zandvoort",
    "slug": "guesthouse-zandvoort",
    "kind": "rental",
    "category": 3,
    "zone": "zandvoort",
    "driveMin": 3,
    "ring": 1,
    "score": 4.5,
    "img": "/images/circuits/zandvoort/guesthouse-zandvoort.jpg"
  },
  {
    "name": "Boutique hotel Novi",
    "slug": "boutique-hotel-novi",
    "kind": "hotel",
    "category": 3,
    "zone": "zandvoort",
    "driveMin": 3,
    "ring": 1,
    "score": 4.5,
    "img": "/images/circuits/zandvoort/boutique-hotel-novi.jpg"
  },
  {
    "name": "Ocean House Zandvoort",
    "slug": "ocean-house-zandvoort",
    "kind": "hotel",
    "category": 3,
    "zone": "zandvoort",
    "driveMin": 3,
    "ring": 1,
    "score": 4.5,
    "img": "/images/circuits/zandvoort/ocean-house-zandvoort.jpg"
  },
  {
    "name": "Hotel Keur",
    "slug": "hotel-keur",
    "kind": "hotel",
    "category": 3,
    "zone": "zandvoort",
    "driveMin": 3,
    "ring": 1,
    "score": 4.5,
    "img": "/images/circuits/zandvoort/hotel-keur.jpg"
  },
  {
    "name": "ZARAS STUDIOS",
    "slug": "zaras-studios",
    "kind": "rental",
    "category": 2,
    "zone": "zandvoort",
    "driveMin": 3,
    "ring": 1,
    "score": 4.2,
    "img": "/images/circuits/zandvoort/zaras-studios.jpg"
  },
  {
    "name": "de Watertoren",
    "slug": "de-watertoren",
    "kind": "hotel",
    "category": 2,
    "zone": "zandvoort",
    "driveMin": 3,
    "ring": 1,
    "score": 4.2,
    "img": "/images/circuits/zandvoort/de-watertoren.jpg"
  },
  {
    "name": "Amsterdam Beach Hotel Zandvoort",
    "slug": "amsterdam-beach-hotel-zandvoort",
    "kind": "hotel",
    "category": 2,
    "zone": "zandvoort",
    "driveMin": 3,
    "ring": 1,
    "score": 4.2,
    "img": "/images/circuits/zandvoort/amsterdam-beach-hotel-zandvoort.jpg"
  },
  {
    "name": "Hotel Paradis",
    "slug": "hotel-paradis",
    "kind": "hotel",
    "category": 2,
    "zone": "zandvoort",
    "driveMin": 3,
    "ring": 1,
    "score": 4.1,
    "img": "/images/circuits/zandvoort/hotel-paradis.jpg"
  },
  {
    "name": "Pension Schier",
    "slug": "pension-schier",
    "kind": "rental",
    "category": 2,
    "zone": "zandvoort",
    "driveMin": 3,
    "ring": 1,
    "score": 3.8,
    "img": "/images/circuits/zandvoort/pension-schier.jpg"
  },
  {
    "name": "Hofje van Maas",
    "slug": "hofje-van-maas",
    "kind": "hotel",
    "category": 1,
    "zone": "zandvoort",
    "driveMin": 3,
    "ring": 1,
    "score": 3.7,
    "img": "/images/circuits/zandvoort/hofje-van-maas.jpg"
  },
  {
    "name": "Palace Hotel",
    "slug": "palace-hotel",
    "kind": "hotel",
    "category": 1,
    "zone": "zandvoort",
    "driveMin": 3,
    "ring": 1,
    "score": 3.6,
    "img": "/images/circuits/zandvoort/palace-hotel.jpg"
  },
  {
    "name": "Hotel Doppenberg",
    "slug": "hotel-doppenberg",
    "kind": "hotel",
    "category": 1,
    "zone": "zandvoort",
    "driveMin": 3,
    "ring": 1,
    "score": 3.5,
    "img": "/images/circuits/zandvoort/hotel-doppenberg.jpg"
  },
  {
    "name": "Hotel Zeespiegel Zandvoort",
    "slug": "hotel-zeespiegel-zandvoort",
    "kind": "hotel",
    "category": 1,
    "zone": "zandvoort",
    "driveMin": 3,
    "ring": 1,
    "score": 3.4,
    "img": "/images/circuits/zandvoort/hotel-zeespiegel-zandvoort.jpg"
  },
  {
    "name": "Holiday Beach House Zandvoort",
    "slug": "holiday-beach-house-zandvoort",
    "kind": "rental",
    "category": 3,
    "zone": "zandvoort",
    "driveMin": 3,
    "ring": 1,
    "score": 5,
    "img": "/images/circuits/zandvoort/holiday-beach-house-zandvoort.jpg"
  },
  {
    "name": "Formule 1 Camping Zandvoort",
    "slug": "formule-1-camping-zandvoort",
    "kind": "camping",
    "category": 3,
    "zone": "santpoort-zuid",
    "driveMin": 8,
    "ring": 1,
    "score": 4.6,
    "img": "/images/circuits/zandvoort/formule-1-camping-zandvoort.jpg"
  }
];
