// Auto-generated by scripts/fetch-zone-photos.mjs.
// A small pool of real ambiance photos per zone (the commune itself), used as
// a fallback on accommodation cards that have no own photo.
export const ZONE_PHOTOS: Record<string, string[]> = {
  "circuit-area": [
    "/images/zones/circuit-area-1.jpg",
    "/images/zones/circuit-area-2.jpg",
    "/images/zones/circuit-area-3.jpg",
    "/images/zones/circuit-area-4.jpg"
  ],
  "le-mans-city-centre": [
    "/images/zones/le-mans-city-centre-1.jpg",
    "/images/zones/le-mans-city-centre-2.jpg",
    "/images/zones/le-mans-city-centre-3.jpg",
    "/images/zones/le-mans-city-centre-4.jpg"
  ],
  "arnage": [
    "/images/zones/arnage-1.jpg",
    "/images/zones/arnage-2.jpg",
    "/images/zones/arnage-3.jpg",
    "/images/zones/arnage-4.jpg"
  ],
  "mulsanne": [
    "/images/zones/mulsanne-1.jpg",
    "/images/zones/mulsanne-2.jpg",
    "/images/zones/mulsanne-3.jpg",
    "/images/zones/mulsanne-4.jpg"
  ],
  "ruaudin": [
    "/images/zones/ruaudin-1.jpg",
    "/images/zones/ruaudin-2.jpg",
    "/images/zones/ruaudin-3.jpg",
    "/images/zones/ruaudin-4.jpg"
  ],
  "change": [
    "/images/zones/change-1.jpg",
    "/images/zones/change-2.jpg",
    "/images/zones/change-3.jpg",
    "/images/zones/change-4.jpg"
  ],
  "ecommoy": [
    "/images/zones/ecommoy-1.jpg",
    "/images/zones/ecommoy-2.jpg",
    "/images/zones/ecommoy-3.jpg",
    "/images/zones/ecommoy-4.jpg"
  ],
  "la-fleche": [
    "/images/zones/la-fleche-1.jpg",
    "/images/zones/la-fleche-2.jpg",
    "/images/zones/la-fleche-3.jpg",
    "/images/zones/la-fleche-4.jpg"
  ],
  "alencon": [
    "/images/zones/alencon-1.jpg",
    "/images/zones/alencon-2.jpg",
    "/images/zones/alencon-3.jpg",
    "/images/zones/alencon-4.jpg"
  ],
  "laval": [
    "/images/zones/laval-1.jpg",
    "/images/zones/laval-2.jpg",
    "/images/zones/laval-3.jpg",
    "/images/zones/laval-4.jpg"
  ],
  "tours": [
    "/images/zones/tours-1.jpg",
    "/images/zones/tours-2.jpg",
    "/images/zones/tours-3.jpg",
    "/images/zones/tours-4.jpg"
  ],
  "angers": [
    "/images/zones/angers-1.jpg",
    "/images/zones/angers-2.jpg",
    "/images/zones/angers-3.jpg",
    "/images/zones/angers-4.jpg"
  ]
};

export const zonePhotos = (zone: string): string[] => ZONE_PHOTOS[zone] ?? [];
